### PR TITLE
Ignore null or blank string-valued span attributes.

### LINKED ISSUE #765: Span::setAttribute null-checking of value may be detrimental
This came up as an issue when working on the auto-instrumentation project.

The ```Span::setAttribute()``` method is commonly used in interceptors to copy attributes from an invocation to span attributes. This method will, by design, throw a ```NullPointerException``` if a null value is supplied. Given that many frameworks may treat certain attributes as optional, there's a chance that attributes with null values are present on the invocation objects.

The current implementation instrumenters/decorators are wrapping the calls to setAttribute() in null-checking if-statements whenever it is suspected that a null value may be supplied.

However, since the exact rules for which attributes may contain null aren't well documented for all frameworks, there's a high risk that a null-check is omitted by mistake, causing hard to find errors at runtime.

Should we implement a ```setAttributeOrNull()``` method that can be used when the presence of null values isn't known? Should we change the behavior of ```setAttribute()```? What is the reason we don't allow null values in the first place? Could we change the behavior to make an assignment of a null value to an attribute a no-op?

### PR DESCRIPTION
**Pull request by jkwatson**
resolves #765

### CODE REVIEW

**Comment by tylerbenson** [comment]
What about setting an attribute on a started span, not the span builder?

**Comment by jkwatson** [comment]
great catch. will update the RERS as well.

**Comment by jkwatson** [comment]
@tylerbenson ok, got the active span as well

File: sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java [hunk 1]
```diff
@@ -137,6 +138,9 @@
 
   @Override
   public Span.Builder setAttribute(String key, String value) {
+    if (StringUtils.isNullOrBlank(value)) {
```
Comment (bogdandrutu) [inline sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java]: Do we want to count this as dropped or we simply ignore?

Comment (jkwatson) [reply sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java]: it's definitely a different kind of "dropping" than the "too many attributes" kind. I think ignoring it is fine..it's not really an attribute at all without a value.

File: sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java [hunk 2]
```diff
@@ -137,6 +138,9 @@
...
+      return this;
+    }
     return setAttribute(key, AttributeValue.stringAttributeValue(value));
```
Comment (bogdandrutu) [inline sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java]: What is the behavior for AttributeValue.stringAttributeValue(value) in case a null string is passed?

File: sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java (hunk 1 above)
Comment (bogdandrutu) [reply sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java]: Fine with this for the moment, may be unexpected for users especially for empty.

File: sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java (hunk 2 above)
Comment (jkwatson) [reply sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java]: that remains the same. If you're trying to create an AttributeValue with a null, you'll get the usual NPE.

Comment (bogdandrutu) [reply sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java]: k

Comment (bogdandrutu) [reply sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java]: I think this is unexpected result and inconsistent, maybe we should try to see how we can offer the same behavior.

Comment (jkwatson) [reply sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java]: that's a fair comment. I think we can do this by allowing null/empty in the `AttributeValue`, and then ignoring when we try to add. I'll change this PR to do it that way.

Comment (jkwatson) [reply sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java]: ok, changed
