### PR TITLE
Restore prior histogram defaults

### LINKED ISSUE #4699: Add config item to restore prior default histogram buckets
We discussed #4684 and #4665 in the SIG meeting on 8/18/2022. While that change does improve spec compliance, it does introduce change that could impact customers who have built tooling around those incorrect, default buckets.

In addition to calling out this change loudly in the release notes / changelog, we also decided to add a short-lived configuration item that will restore the prior behavior. With that, simply setting an environment var or system property will allow the user to get the prior defaults.

### PR DESCRIPTION
**Pull request by jack-berg**
Builds on #4684. (Need to rebase after merging.)

Resolves #4699.

### CODE REVIEW

File: sdk/metrics/src/configurationTest/java/io/opentelemetry/sdk/metrics/internal/aggregator/ExplicitBucketHistogramUtilsTest.java [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+import static org.assertj.core.api.Assertions.assertThat;
+
+import java.util.Arrays;
+import org.junit.jupiter.api.Test;
+
+class ExplicitBucketHistogramUtilsTest {
+
+  /**
+   * {@link ExplicitBucketHistogramUtils#getDefaultBucketBoundaries()} returns different values when
+   * {@code otel.java.histogram.legacy.buckets.enabled=true}.
```
Comment (breedx-splk) [inline sdk/metrics/src/configurationTest/java/io/opentelemetry/sdk/metrics/internal/aggregator/ExplicitBucketHistogramUtilsTest.java:17]: Maybe a note that this is set in the `build.gradle.kts` for this module?

**Review by breedx-splk — APPROVED** [review]
Looks good to me. No real surprises and matches what we discussed.

**Review by jkwatson — APPROVED** [review]
