### PR TITLE
Fix race condition of `GlobalOpenTelemetry` initialization with `AutoConfiguredOpenTelemetrySdkBuilder`

### LINKED ISSUE #7354: Race-condition of GlobalOpenTelemetry initialization with AutoConfiguredOpenTelemetrySdkBuilder
After upgrading our distro to the latest upstream version, one of our E2E tests suddenly started failing.
To me it looks like #7255 unfortunately introduced (or rather surfaced) a race-condition:

The agent uses the `AutoConfiguredOpenTelemetrySdkBuilder` directly to register the `GlobalOpenTelemetry` instance in [OpenTelemetryInstaller](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/OpenTelemetryInstaller.java). Therefore, it does not hold the `mutex` from `GlobalOpenTelemetry` while building the SDK.

In our E2E test we define a metrics-exporter with a very low export interval (e.g. 10ms). In this case it can happen that this exporter attempts to run before `AutoConfiguredOpenTelemetrySdkBuilder` has finished installing the `GlobalOpenTelemetry` instance. Due to #7255, this will result in the exporter calling `GlobalOpenTelemetry.get()`, effectively triggering a nested, wrong autoconfiguration.

I don't think this is a critical bug, because such low export intervals are likely to be used only in tests. Nonetheless I think we should fix the underlying issue. One approach would be to make `AutoConfiguredOpenTelemetrySdkBuilder.build()` hold the mutex from `GlobalOpenTelemetry` while building the SDK, if the builder was configured to install the SDK globally.

<details>
  <summary>Error logs</summary>
  
  ```
      2025-05-19 10:58:05,256 [main] INFO  io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder - Error encountered during autoconfiguration. Closing partially configured components.
    2025-05-19 10:58:05,260 [PeriodicMetricReader-1] ERROR io.opentelemetry.exporter.internal.http.HttpExporter - Failed to export metrics. The request could not be executed. Full error message: executor rejected
    java.io.InterruptedIOException: executor rejected
    	at okhttp3.internal.connection.RealCall$AsyncCall.executeOn(RealCall.kt:501) ~[agent.jar:1.4.2-SNAPSHOT]
    	at okhttp3.Dispatcher.promoteAndExecute(Dispatcher.kt:184) ~[agent.jar:1.4.2-SNAPSHOT]
    	at okhttp3.Dispatcher.enqueue$okhttp(Dispatcher.kt:125) ~[agent.jar:1.4.2-SNAPSHOT]
    	at okhttp3.internal.connection.RealCall.enqueue(RealCall.kt:164) ~[agent.jar:1.4.2-SNAPSHOT]
    	at io.opentelemetry.exporter.sender.okhttp.internal.OkHttpHttpSender.lambda$send$2(OkHttpHttpSender.java:139) ~[agent.jar:1.4.2-SNAPSHOT]
    	at io.opentelemetry.javaagent.shaded.io.opentelemetry.context.Context.lambda$wrap$1(Context.java:241) ~[?:1.4.2-SNAPSHOT]
    	at io.opentelemetry.javaagent.shaded.io.opentelemetry.api.internal.InstrumentationUtil.suppressInstrumentation(InstrumentationUtil.java:28) ~[?:1.4.2-SNAPSHOT]
    	at io.opentelemetry.exporter.sender.okhttp.internal.OkHttpHttpSender.send(OkHttpHttpSender.java:135) ~[agent.jar:1.4.2-SNAPSHOT]
    	at io.opentelemetry.exporter.internal.http.HttpExporter.export(HttpExporter.java:63) ~[agent.jar:1.4.2-SNAPSHOT]
    	at io.opentelemetry.exporter.internal.otlp.metrics.MetricReusableDataMarshaler.export(MetricReusableDataMarshaler.java:48) [agent.jar:1.4.2-SNAPSHOT]
    	at io.opentelemetry.exporter.otlp.http.metrics.OtlpHttpMetricExporter.export(OtlpHttpMetricExporter.java:113) [agent.jar:1.4.2-SNAPSHOT]
    	at co.elastic.otel.dynamicconfig.BlockableMetricExporter.export(BlockableMetricExporter.java:70) [agent.jar:1.4.2-SNAPSHOT]
    	at io.opentelemetry.sdk.metrics.export.PeriodicMetricReader$Scheduled.doRun(PeriodicMetricReader.java:167) [agent.jar:1.4.2-SNAPSHOT]
    	at io.opentelemetry.sdk.metrics.export.PeriodicMetricReader$Scheduled.run(PeriodicMetricReader.java:153) [agent.jar:1.4.2-SNAPSHOT]
    	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
    	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
    	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
    	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
    Caused by: java.util.concurrent.RejectedExecutionException: Task okhttp3.internal.connection.RealCall$AsyncCall@2429452d rejected from java.util.concurrent.ThreadPoolExecutor@3bfc0e36[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
    	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065) ~[?:?]
    	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833) ~[?:?]
    	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365) ~[?:?]
    	at okhttp3.internal.connection.RealCall$AsyncCall.executeOn(RealCall.kt:498) ~[agent.jar:1.4.2-SNAPSHOT]
    	... 19 more
    2025-05-19 10:58:05,268 [main] INFO  io.opentelemetry.exporter.internal.http.HttpExporter - Calling shutdown() multiple times.
    2025-05-19 10:58:05,269 [main] INFO  io.opentelemetry.exporter.internal.http.HttpExporter - Calling shutdown() multiple times.
    10:58:05.272 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: io.opentelemetry.sdk.autoconfigure.spi.ConfigurationException: Unexpected configuration error
    10:58:05.272 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder.build(AutoConfiguredOpenTelemetrySdkBuilder.java:489)
    10:58:05.272 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at io.opentelemetry.javaagent.tooling.OpenTelemetryInstaller.installOpenTelemetrySdk(OpenTelemetryInstaller.java:29)
    2025-05-19 10:58:05,270 [main] INFO  io.opentelemetry.exporter.internal.http.HttpExporter - Calling shutdown() multiple times.
    2025-05-19 10:58:05,271 [main] INFO  io.opentelemetry.exporter.internal.http.HttpExporter - Calling shutdown() multiple times.
    10:58:05.273 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:160)
    10:58:05.273 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:110)
    10:58:05.273 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at io.opentelemetry.javaagent.tooling.AgentStarterImpl.start(AgentStarterImpl.java:101)
    10:58:05.273 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at io.opentelemetry.javaagent.bootstrap.AgentInitializer$2.run(AgentInitializer.java:66)
    10:58:05.273 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at io.opentelemetry.javaagent.bootstrap.AgentInitializer$2.run(AgentInitializer.java:60)
    10:58:05.273 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.execute(AgentInitializer.java:82)
    10:58:05.273 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:59)
    10:58:05.273 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at io.opentelemetry.javaagent.OpenTelemetryAgent.startAgent(OpenTelemetryAgent.java:59)
    10:58:05.273 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:46)
    10:58:05.273 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at co.elastic.otel.agent.ElasticAgent.premain(ElasticAgent.java:39)
    10:58:05.273 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    10:58:05.273 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    10:58:05.273 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    10:58:05.273 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
    10:58:05.273 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:491)
    10:58:05.273 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:503)
    10:58:05.273 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: Caused by: java.lang.IllegalStateException: GlobalOpenTelemetry.set has already been called. GlobalOpenTelemetry.set must be called only once before any calls to GlobalOpenTelemetry.get. If you are using the OpenTelemetrySdk, use OpenTelemetrySdkBuilder.buildAndRegisterGlobal instead. Previous invocation set to cause of this exception.
    10:58:05.274 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at io.opentelemetry.javaagent.shaded.io.opentelemetry.api.GlobalOpenTelemetry.set(GlobalOpenTelemetry.java:107)
    10:58:05.274 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder.maybeSetAsGlobal(AutoConfiguredOpenTelemetrySdkBuilder.java:580)
    10:58:05.274 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder.build(AutoConfiguredOpenTelemetrySdkBuilder.java:470)
    10:58:05.274 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	... 17 more
    10:58:05.274 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: Caused by: java.lang.Throwable
    10:58:05.274 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at io.opentelemetry.javaagent.shaded.io.opentelemetry.api.GlobalOpenTelemetry.set(GlobalOpenTelemetry.java:115)
    10:58:05.274 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at io.opentelemetry.javaagent.shaded.io.opentelemetry.api.GlobalOpenTelemetry.get(GlobalOpenTelemetry.java:85)
    10:58:05.274 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at io.opentelemetry.javaagent.shaded.io.opentelemetry.api.GlobalOpenTelemetry.getMeterProvider(GlobalOpenTelemetry.java:174)
    10:58:05.274 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at io.opentelemetry.exporter.internal.ExporterMetrics.meter(ExporterMetrics.java:90)
    10:58:05.274 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at io.opentelemetry.exporter.internal.ExporterMetrics.seen(ExporterMetrics.java:74)
    10:58:05.274 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at io.opentelemetry.exporter.internal.ExporterMetrics.addSeen(ExporterMetrics.java:58)
    10:58:05.274 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at io.opentelemetry.exporter.internal.http.HttpExporter.export(HttpExporter.java:59)
    10:58:05.274 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at io.opentelemetry.exporter.internal.otlp.metrics.MetricReusableDataMarshaler.export(MetricReusableDataMarshaler.java:48)
    10:58:05.274 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at io.opentelemetry.exporter.otlp.http.metrics.OtlpHttpMetricExporter.export(OtlpHttpMetricExporter.java:113)
    10:58:05.274 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at co.elastic.otel.dynamicconfig.BlockableMetricExporter.export(BlockableMetricExporter.java:70)
    10:58:05.274 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at io.opentelemetry.sdk.metrics.export.PeriodicMetricReader$Scheduled.doRun(PeriodicMetricReader.java:167)
    10:58:05.274 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at io.opentelemetry.sdk.metrics.export.PeriodicMetricReader$Scheduled.run(PeriodicMetricReader.java:153)
    10:58:05.274 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    10:58:05.274 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
    10:58:05.274 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
    10:58:05.274 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    10:58:05.274 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    10:58:05.274 [docker-java-stream-2559052] INFO  c.e.j.smoketest.UserAgentHeaderTest - STDERR: 	at java.base/java.lang.Thread.run(Thread.java:840)
  ```
  
</details>

### PR DESCRIPTION
**Pull request by fandreuz**
Fixes #7354.

~~Not sure if reflection is the best way to achieve this, I've seen it's quite used in the SDK to hide things that should not be directly exposed to the users. Let me know if a proper API exposed by `GlobalOpenTelemetry` would be more appropriate.~~

### CODE REVIEW

**Review by jack-berg — COMMENTED** [review]
I don't love the idea of accessing the GlobalOpenTelemetry's private mutex reflectively...

Could we achieve the same effect by adding `GlobalOpenTelemetry#set(Supplier<OpenTelemetry> supplier)`, with an implementation that obtains the the lock on `mutex` before calling `Supplier.get()`?

**Comment by fandreuz** [comment]
Sure, check 6afffc35b368509009bad794f055f62ee53d9f4f

**Comment by fandreuz** [comment]
I made `AutoConfiguredOpenTelemetrySdk` an instance of `OpenTelemetry` to allow a `Supplier<AutoConfiguredOpenTelemetrySdk>` to be passed to a function expecting a `Supplier<T extends OpenTelemetry>`. This made sense to me and simplified the implementation, let me know if you see any problem with this approach.

File: api/all/src/main/java/io/opentelemetry/api/GlobalOpenTelemetry.java [hunk 1]
```diff
@@ -116,6 +118,21 @@ public static void set(OpenTelemetry openTelemetry) {
...
   }
 
+  /**
+   * Sets the {@link OpenTelemetry} that should be the global instance.
+   *
+   * <p>This method calls the given {@code supplier}, converts the output to an {@link
+   * OpenTelemetry} object, and finally calls {@link #set(OpenTelemetry)}, all while holding the
+   * {@link GlobalOpenTelemetry} mutex.
+   */
+  public static <T> T set(Supplier<T> supplier, Function<T, OpenTelemetry> converter) {
```
Comment (jack-berg) [inline api/all/src/main/java/io/opentelemetry/api/GlobalOpenTelemetry.java]: What about something like: https://github.com/open-telemetry/opentelemetry-java/commit/5f06de2b8aeca6a41157a88d3abaab3bd23dbded

This API signature will look strange outside of the autoconfigure use case.

I like this approach in general though and would love to get it merged!

Comment (fandreuz) [reply api/all/src/main/java/io/opentelemetry/api/GlobalOpenTelemetry.java]: Yeah I didn't like that signature either, your commit made it look much better. I chery-picked it into my branch

**Comment by jkwatson** [comment]
Won't this lead to some difficult situations where someone has a long-lived handle to an instance that they got from GlobalOpenTelemetry.get() which is no longer the "active" instance? Have we thoroughly thought through the implications of that? Will this behavior be surprising when we support dynamically changing the behavior of GlobalOpenTelemetry via (eg.) opamp?

**Comment by jkwatson** [comment]
> Won't this lead to some difficult situations where someone has a long-lived handle to an instance that they got from GlobalOpenTelemetry.get() which is no longer the "active" instance? Have we thoroughly thought through the implications of that? Will this behavior be surprising when we support dynamically changing the behavior of GlobalOpenTelemetry via (eg.) opamp?

never mind. I missed that `set` still doesn't let you change the global instance. No problem then! Looks good!

**Comment by jkwatson** [comment]
Can we write a unit test that verifies that this fixes the race condition?

**Comment by fandreuz** [comment]
> Can we write a unit test that verifies that this fixes the race condition?

A fully deterministic reproducer would be relatively hard to write for this issue since it's a race condition. I could do that, but I'd probably have to resort to artificial sleeps to reproduce the conditions for the race. Would such a test be acceptable @jkwatson ?

**Comment by jkwatson** [comment]
> > Can we write a unit test that verifies that this fixes the race condition?
> 
> A fully deterministic reproducer would be relatively hard to write for this issue since it's a race condition. I could do that, but I'd probably have to resort to artificial sleeps to reproduce the conditions for the race. Would such a test be acceptable @jkwatson ?

Yes, better than no test at all, so we don't accidentally re-introduce the issue in the future.

**Comment by fandreuz** [comment]
Hi @jkwatson, please check the new test in `AutoConfiguredOpenTelemetrySdkTest`

File: sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkTest.java [hunk 2]
```diff
@@ -674,4 +678,53 @@ void configurationError_ClosesResources() {
...
+              });
+
+      AutoConfiguredOpenTelemetrySdk autoConfiguredOpenTelemetrySdk =
+          builder.setResultAsGlobal().build();
+
+      assertThat(gotGetResult.poll(3, TimeUnit.SECONDS))
+          .extracting("delegate")
+          .isSameAs(autoConfiguredOpenTelemetrySdk.getOpenTelemetrySdk());
+    }
+  }
```
Comment (jack-berg) [inline sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkTest.java]: Here's a version that avoids static mocks:
```suggestion
  @Test
  void globalOpenTelemetryLock() throws InterruptedException, ExecutionException, TimeoutException {
    CountDownLatch autoconfigStarted = new CountDownLatch(1);
    CountDownLatch completeAutoconfig = new CountDownLatch(1);
    ExecutorService executorService = Executors.newFixedThreadPool(2);

    // Submit a future to autoconfigure the SDK and set the result as global. Add a customization
    // hook which blocks until we say so.
    CompletableFuture<OpenTelemetrySdk> autoConfiguredOpenTelemetryFuture =
        CompletableFuture.supplyAsync(
            () ->
                builder
                    .addLoggerProviderCustomizer(
                        (sdkLoggerProviderBuilder, configProperties) -> {
                          autoconfigStarted.countDown();
                          try {
                            completeAutoconfig.await();
                          } catch (InterruptedException e) {
                            Thread.currentThread().interrupt();
                          }
                          return sdkLoggerProviderBuilder;
                        })
                    .setResultAsGlobal()
                    .build()
                    .getOpenTelemetrySdk(),
            executorService);

    // Wait for autoconfiguration to enter our callback, then try to get an instance of
    // GlobalOpenTelemetry. GlobalOpenTelemetry.get() should block until we release the
    // completeAutoconfig latch and allow autoconfiguration to complete.
    autoconfigStarted.await();
    CompletableFuture<OpenTelemetry> globalOpenTelemetryFuture =
        CompletableFuture.supplyAsync(GlobalOpenTelemetry::get, executorService);
    Thread.sleep(10);
    assertThat(globalOpenTelemetryFuture.isDone()).isFalse();
    assertThat(autoConfiguredOpenTelemetryFuture.isDone()).isFalse();

    // Release the latch, allowing autoconfiguration to complete. Confirm that our
    // GlobalOpenTelemetry.get() future resolved to the same instance as autoconfiguration.
    completeAutoconfig.countDown();
    assertThat(unobfuscate(globalOpenTelemetryFuture.get(10, TimeUnit.SECONDS)))
        .isSameAs(autoConfiguredOpenTelemetryFuture.get(10, TimeUnit.SECONDS));

    // Cleanup
    executorService.shutdown();
    autoConfiguredOpenTelemetryFuture.get().shutdown().join(10, TimeUnit.SECONDS);
    GlobalOpenTelemetry.resetForTest();
  }

  private static OpenTelemetry unobfuscate(OpenTelemetry openTelemetry) {
    try {
      Field delegateField =
          Class.forName("io.opentelemetry.api.GlobalOpenTelemetry$ObfuscatedOpenTelemetry")
              .getDeclaredField("delegate");
      delegateField.setAccessible(true);
      Object delegate = delegateField.get(openTelemetry);
      return (OpenTelemetry) delegate;
    } catch (NoSuchFieldException | IllegalAccessException | ClassNotFoundException e) {
      throw new IllegalStateException("Error unobfuscating OpenTelemetry", e);
    }
  }
```

Comment (fandreuz) [reply sdk-extensions/autoconfigure/src/test/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkTest.java]: Thanks @jack-berg, that looks better indeed! I applied the suggestion

**Review by jack-berg — APPROVED** [review]
Looks good. @jkwatson there's a unit test now for this. Any additional resevations?

**Comment by jkwatson** [comment]
> Looks good. @jkwatson there's a unit test now for this. Any additional resevations?

🚢
