### PR TITLE
Fix ConfigUtil#getString ConcurrentModificationException

### LINKED ISSUE #6732: ConcurrentModificationException in ConfigUtil
**Describe the bug**
There is a `ConcurrentModificationException` thrown while calling `build()` on `LongGaugeBuilder`.

**Steps to reproduce**
not yet

**What did you expect to see?**
No exception thrown

**What did you see instead?**
`ConcurrentModificationException`

**What version and what artifacts are you using?**
Artifacts: see `*.gradle.kts` excerpt below
Version: 1.42.1
How did you reference these artifacts? 
```
implementation(platform("io.opentelemetry:opentelemetry-bom:1.42.1"))
implementation("io.opentelemetry:opentelemetry-context")
implementation("io.opentelemetry:opentelemetry-api")
implementation("io.opentelemetry:opentelemetry-exporter-common")
implementation("io.opentelemetry:opentelemetry-exporter-otlp")
implementation("io.opentelemetry:opentelemetry-exporter-logging")
implementation("io.opentelemetry:opentelemetry-extension-kotlin")
implementation("io.opentelemetry:opentelemetry-api-incubator")
implementation("io.opentelemetry:opentelemetry-extension-kotlin")
implementation("io.opentelemetry:opentelemetry-sdk")
  ```

**Environment**
Compiler: JDK 17 - Temurin
OS: Ubuntu (unknown version)
Runtime (if different from JDK above): Android runtime (ART)
OS (if different from OS compiled on): Android 

**Additional context**
```
  Caused by java.util.ConcurrentModificationException:
at java.util.Hashtable$Enumerator.next(Hashtable.java:1397)
at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:133)
at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:489)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:475)
at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:236)
at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:482)
at io.opentelemetry.api.internal.ConfigUtil.getString(ConfigUtil.java:40)
at io.opentelemetry.sdk.metrics.internal.debug.DebugConfig.<clinit>(DebugConfig.java:25)
at io.opentelemetry.sdk.metrics.internal.debug.SourceInfo.fromCurrentStack(SourceInfo.java:45)
at io.opentelemetry.sdk.metrics.internal.descriptor.InstrumentDescriptor.<init>(InstrumentDescriptor.java:25)
at io.opentelemetry.sdk.metrics.internal.descriptor.AutoValue_InstrumentDescriptor.<init>(AutoValue_InstrumentDescriptor.java:28)
at io.opentelemetry.sdk.metrics.internal.descriptor.InstrumentDescriptor.create(InstrumentDescriptor.java:35)
at io.opentelemetry.sdk.metrics.InstrumentBuilder.newDescriptor(InstrumentBuilder.java:111)
at io.opentelemetry.sdk.metrics.InstrumentBuilder.buildSynchronousInstrument(InstrumentBuilder.java:78)
at io.opentelemetry.sdk.metrics.SdkLongGauge$SdkLongGaugeBuilder.build(SdkLongGauge.java:96)
at io.opentelemetry.sdk.metrics.SdkLongGauge$SdkLongGaugeBuilder.build(SdkLongGauge.java:58) 
```

### PR DESCRIPTION
**Pull request by jack-berg**
Resolves #6732.

Builds on #6746.

### CODE REVIEW

File: api/all/src/test/java/io/opentelemetry/api/internal/ConfigUtilTest.java [hunk 1]
```diff
@@ -56,4 +64,45 @@ void defaultIfnull() {
     assertThat(ConfigUtil.defaultIfNull("val1", "val2")).isEqualTo("val1");
     assertThat(ConfigUtil.defaultIfNull(null, "val2")).isEqualTo("val2");
   }
+
+  @Test
+  @SuppressWarnings("ReturnValueIgnored")
+  void systemPropertiesConcurrentAccess() throws ExecutionException, InterruptedException {
```
Comment (jack-berg) [inline api/all/src/test/java/io/opentelemetry/api/internal/ConfigUtilTest.java:70]: This test fails on java 8 if you call `System.getProperties()` instead of `ConfigUtil#safeSystemProperties()`.

File: api/all/src/main/java/io/opentelemetry/api/internal/ConfigUtil.java [hunk 2]
```diff
@@ -19,6 +21,17 @@ public final class ConfigUtil {
...
 
+  /**
+   * Returns a copy of system properties which is safe to iterate over.
+   *
+   * <p>In java 8 and android environments, iterating through system properties may trigger {@link
+   * ConcurrentModificationException}. This method ensures callers can iterate safely without risk
+   * of exception. See https://github.com/open-telemetry/opentelemetry-java/issues/6732 for details.
+   */
+  public static Properties safeSystemProperties() {
+    return (Properties) System.getProperties().clone();
```
Comment (jack-berg) [inline api/all/src/main/java/io/opentelemetry/api/internal/ConfigUtil.java:32]: Cloning seems to be the simplest way to accommodate various use cases. Anything other option that returns `Properties` ends up mimicking the logic of `clone()` anyway. If `clone()` ends up being too expensive (I doubt it), we can cache a copy.

Comment (trask) [reply api/all/src/main/java/io/opentelemetry/api/internal/ConfigUtil.java:32]: I'm ok with it

`ConfigUtil.getString(..)` is already slow (too slow to be used on the hotpath) since it normalizes all the entry keys on each call

**Review by trask — APPROVED** [review]

File: api/all/src/main/java/io/opentelemetry/api/internal/ConfigUtil.java (hunk 2 above)
Comment (laurit) [reply api/all/src/main/java/io/opentelemetry/api/internal/ConfigUtil.java:32]: >  If clone() ends up being too expensive

`clone` is only needed on jdk8 and android so we could skip it on other jdks if we so wish. Untested code follows
```java
private static final CLONE_PROPERTIES = System.getProperty("java.version").equals("0") // android
  || System.getProperty("java.specification.version").startsWith("1."); // jdk8
```

Comment (jack-berg) [reply api/all/src/main/java/io/opentelemetry/api/internal/ConfigUtil.java:32]: > clone is only needed on jdk8 and android so we could skip it on other jdks if we so wish.

That's true. I'd prefer to keep that in our back pocket in case we need it. As a general rule, I think we avoid runtime-specific code unless we have a strong reason (subjective definition of "strong").
