### PR TITLE
validate version from traceparent according to spec

### LINKED ISSUE #1674: traceparent  with invalid version is not rejected
Next w3c context propagation tests fails:
```
def test_traceparent_version_0xff(self):
		'''
		harness sends an invalid traceparent with version 255 (0xff)
		expects a valid traceparent from the output header, with a newly generated trace_id
		'''
		traceparent, tracestate = self.make_single_request_and_get_tracecontext([
			['traceparent', 'ff-12345678901234567890123456789012-1234567890123456-01'],
		])
		self.assertNotEqual(traceparent.trace_id.hex(), '12345678901234567890123456789012')

def test_traceparent_version_illegal_characters(self):
		'''
		harness sends an invalid traceparent with illegal characters in version
		expects a valid traceparent from the output header, with a newly generated trace_id
		'''
		traceparent, tracestate = self.make_single_request_and_get_tracecontext([
			['traceparent', '.0-12345678901234567890123456789012-1234567890123456-01'],
		])
		self.assertNotEqual(traceparent.trace_id.hex(), '12345678901234567890123456789012')
```

Got in https://github.com/open-telemetry/opentelemetry-java/pull/1653
Can be reproduced by running tests from mentioned PR.

spec: https://www.w3.org/TR/trace-context/#version

### PR DESCRIPTION
**Pull request by malafeev**
fix #1674 

spec: https://www.w3.org/TR/trace-context/#version

### CODE REVIEW

**Comment by Oberon00** [comment]
This violates the spec. See point 4 in https://www.w3.org/TR/trace-context/#a-traceparent-is-received:

> If the version number is higher than supported by the tracer, the vendor uses the format defined in this specification (00) to parse trace-id and parent-id. The vendor will only parse the trace-flags values supported by this version of this specification and ignore all other values. If parsing fails, the vendor creates a new traceparent header and deletes the tracestate. Vendors will set all unparsed / unknown trace-flags to 0 on outgoing requests.

**Review by Oberon00 — CHANGES_REQUESTED** [review]
This violates the W3C spec. See point 4 in https://www.w3.org/TR/trace-context/#a-traceparent-is-received:

> If the version number is higher than supported by the tracer, the vendor uses the format defined in this specification (00) to parse trace-id and parent-id. The vendor will only parse the trace-flags values supported by this version of this specification and ignore all other values. If parsing fails, the vendor creates a new traceparent header and deletes the tracestate. Vendors will set all unparsed / unknown trace-flags to 0 on outgoing requests.

**Comment by malafeev** [comment]
@Oberon00 I added only validation that version is valid. I don't want to change parsing of traceparent based on version number in this PR.

**Review by Oberon00 — APPROVED** [review]
Sorry, that was entirely my fault. Instead of reading `isValid`, I just assumed it would check for `== "00"`

File: api/src/main/java/io/opentelemetry/trace/TraceVersion.java [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package io.opentelemetry.trace;
+
+public class TraceVersion {
```
Comment (Oberon00) [inline api/src/main/java/io/opentelemetry/trace/TraceVersion.java:19]:
```suggestion
final class TraceVersion {
```

File: api/src/main/java/io/opentelemetry/trace/propagation/HttpTraceContext.java [hunk 2]
```diff
@@ -198,6 +199,11 @@ private static SpanContext extractContextFromTraceParent(String traceparent) {
     }
 
     try {
+      String version = traceparent.substring(0, 2);
```
Comment (Oberon00) [inline api/src/main/java/io/opentelemetry/trace/propagation/HttpTraceContext.java:202]: Shouldn't we check whether there is a trailing `-` too? What does W3C say?

File: api/src/main/java/io/opentelemetry/trace/TraceVersion.java (hunk 1 above)
Comment (malafeev) [reply api/src/main/java/io/opentelemetry/trace/TraceVersion.java:19]: it cannot be package private because accessed outside of pakcage

Comment (Oberon00) [reply api/src/main/java/io/opentelemetry/trace/TraceVersion.java:19]: You can move it to the right package though. Or just make it a member function of `HttpTraceContext`

Comment (jkwatson) [inline api/src/main/java/io/opentelemetry/trace/TraceVersion.java:19]: I'm not sure we need a whole class just for one method. Could this just be a method on the HttpTraceContext itself?

File: api/src/main/java/io/opentelemetry/trace/propagation/HttpTraceContext.java (hunk 2 above)
Comment (malafeev) [reply api/src/main/java/io/opentelemetry/trace/propagation/HttpTraceContext.java:202]: it's already checked above:
```
traceparent.charAt(TRACE_ID_OFFSET - 1) == TRACEPARENT_DELIMITER
```

File: api/src/main/java/io/opentelemetry/trace/TraceVersion.java (hunk 1 above)
Comment (malafeev) [reply api/src/main/java/io/opentelemetry/trace/TraceVersion.java:19]: because `BigendianEncoding` class is package private and I cannot call it.

Comment (malafeev) [reply api/src/main/java/io/opentelemetry/trace/TraceVersion.java:19]: no, problem that I want to call `BigendianEncoding.isValidBase16String(...)` method, but class `BigendianEncoding` is package private in `io.opentelemetry.trace`.

but `HttpTraceContext` class in package `io.opentelemetry.trace.propagation`.

So I need to make TraceVersion public class in package `io.opentelemetry.trace`.
Or move class  `HttpTraceContext` to package `io.opentelemetry.trace`.

Comment (jkwatson) [reply api/src/main/java/io/opentelemetry/trace/TraceVersion.java:19]: I think I'd prefer a 3rd option, which is to create a public utility class (called maybe something like "WireFormatUtils"?) that will provide these needed methods for any propagator that needs them. This could then delegate to the BigEndianEncoding implementation, as appropriate, or maybe we move methods in there, as appropriate.

Comment (anuraaga) [reply api/src/main/java/io/opentelemetry/trace/TraceVersion.java:19]: It's just two bytes - I think I would just generate a `Set` of all possible versions as a private in `HttpTraceContext` (255 elements only) and use that for validation, seems like it could be faster anyways.

Comment (malafeev) [reply api/src/main/java/io/opentelemetry/trace/TraceVersion.java]: renamed TraceVersion to WireFormatUtils with method

File: api/src/main/java/io/opentelemetry/trace/WireFormatUtils.java [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package io.opentelemetry.trace;
+
+public class WireFormatUtils {
```
Comment (anuraaga) [inline api/src/main/java/io/opentelemetry/trace/WireFormatUtils.java:19]: This is a sort of strange public API - not clear what wire format or version this is referring to, and pretty narrow use case. I think this was added because of the visibility of `BigEndianEncoding` but how about my suggestion of just precomputing the possible valid values and comparing to avoid needing this?

Comment (malafeev) [reply api/src/main/java/io/opentelemetry/trace/WireFormatUtils.java:19]: set of 255 strings is not tiny. how I can compute all 255 values to insert into set? I suppose I will need to call `BigEndianEncoding.byteToBase16String(...)` method which is in `BigEndianEncoding` class.

Comment (anuraaga) [reply api/src/main/java/io/opentelemetry/trace/WireFormatUtils.java:19]: Well since this is on the slow path (static initializer), we don't quite need the performance of `BigEndianEncoding` and could just use `Long.toHexString`.

```
Set<String> VALID_VERSIONS = new HashSet<>();
for (int i = 0; i < 255; i++) {
  String version = Long.toHexString(i);
  if (version.length() < 2)
    version = '0' + version;
  VALID_VERSIONS.add(version);
}
```

It's not so bad I guess. We need to be careful with public API, for this I would probably copy rather than expose if we need to.

Comment (jkwatson) [reply api/src/main/java/io/opentelemetry/trace/WireFormatUtils.java:19]: I think the suggestion is to write some quick code to generate all the possibilities, and then just put that into a static Set field. Is that what you were thinking, @anuraaga ?

Comment (malafeev) [reply api/src/main/java/io/opentelemetry/trace/WireFormatUtils.java]: done

Comment (malafeev) [reply api/src/main/java/io/opentelemetry/trace/WireFormatUtils.java]: I added initialization to `static` block, can move to method if it's better

File: api/src/main/java/io/opentelemetry/trace/TraceVersion.java (hunk 1 above)
Comment (malafeev) [reply api/src/main/java/io/opentelemetry/trace/TraceVersion.java]: removed

Comment (malafeev) [reply api/src/main/java/io/opentelemetry/trace/TraceVersion.java]: done

File: api/src/main/java/io/opentelemetry/trace/WireFormatUtils.java (hunk 3 above)
Comment (jkwatson) [reply api/src/main/java/io/opentelemetry/trace/WireFormatUtils.java]: The other option would be to pre-generate the set and hard-code it into the code itself, but I think this is fine a few extra microseconds at startup shouldn't be an issue, and we can change it to a hard-coded set later if we want.

**Review by jkwatson — APPROVED** [review]

**Review by anuraaga — APPROVED** [review]
Thanks!
