### PR TITLE
Remove duplicative FINEST-level error logging in GrpcExporter

### LINKED ISSUE #8098: Do we need to log OTLP errors at SEVERE and FINEST?
Copy / pasted from [GrpcExporter](https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/common/src/main/java/io/opentelemetry/exporter/internal/grpc/GrpcExporter.java#L123-L139), which has a similar, but not identical, harness / wrapper around `GrpcSender`.

Tracked the lineage of where this additional finest level logging came from and its ancient: https://github.com/open-telemetry/opentelemetry-java/pull/1803/changes#diff-b81bcc3e91a1ea9ee5f99b101f968b51a9396151014479db2f00e419394b573fR149

But it does seem duplicative. At the `SEVERE` level, the exception is included, and thus _can_ be printed if the user has configured their logging framework to do so. At the `FINEST` level, the stacktrace is printed as part of the log message regardless of logging framework config.

_Originally posted by @jack-berg in https://github.com/open-telemetry/opentelemetry-java/pull/8046#discussion_r2818518375_

### PR DESCRIPTION
**Pull request by VamshikrishnaMonagari**
The `onError` method in `GrpcExporter` logged failures twice: once at `SEVERE` (with the exception object) and again at `FINEST`. The `FINEST` log is redundant since anyone who configures their logging framework to display stack traces will get them from the `SEVERE` log's exception parameter.

`HttpExporter` does not have this pattern and required no changes.

Resolves #8098

### CODE REVIEW

File: exporters/common/src/main/java/io/opentelemetry/exporter/internal/grpc/GrpcExporter.java [hunk 1]
```diff
@@ -132,9 +132,6 @@ private void onError(
             + "s. The request could not be executed. Error message: "
             + e.getMessage(),
         e);
-    if (logger.isLoggable(Level.FINEST)) {
-      logger.log(Level.FINEST, "Failed to export " + type + "s. Details follow: " + e);
```
Comment (jkwatson) [inline exporters/common/src/main/java/io/opentelemetry/exporter/internal/grpc/GrpcExporter.java:136]: I think the intention was to get the stacktrace here at FINEST level, so this wouldn't be redundant. In practice, I don't know if this actually does that. But, I think if we could change this to actually include the stacktrace, that would be the better fix.

Comment (VamshikrishnaMonagari) [reply exporters/common/src/main/java/io/opentelemetry/exporter/internal/grpc/GrpcExporter.java:136]: ah yeah, that makes sense, the original was just concatenating the exception into the string and doesn't include the stack trace. Updated to pass `e` as the Throwable parameter so the logging framework renders the full stack trace.

**Review by jkwatson — APPROVED** [review]

File: exporters/common/src/main/java/io/opentelemetry/exporter/internal/grpc/GrpcExporter.java [hunk 2]
```diff
@@ -133,7 +133,7 @@ private void onError(
             + e.getMessage(),
         e);
     if (logger.isLoggable(Level.FINEST)) {
-      logger.log(Level.FINEST, "Failed to export " + type + "s. Details follow: " + e);
+      logger.log(Level.FINEST, "Failed to export " + type + "s. Details follow:", e);
```
Comment (jack-berg) [inline exporters/common/src/main/java/io/opentelemetry/exporter/internal/grpc/GrpcExporter.java:136]: We actually have inconsistent and probably bad patterns around this in other places:

In these cases we log both the exception message and record the the exception itself:

https://github.com/open-telemetry/opentelemetry-java/blob/9a992c2e6bd71735db55fc0870edba5e1891e92c/exporters/common/src/main/java/io/opentelemetry/exporter/internal/grpc/GrpcExporter.java#L133-L134

https://github.com/open-telemetry/opentelemetry-java/blob/9a992c2e6bd71735db55fc0870edba5e1891e92c/exporters/common/src/main/java/io/opentelemetry/exporter/internal/http/HttpExporter.java#L119-L125

https://github.com/open-telemetry/opentelemetry-java/blob/9a992c2e6bd71735db55fc0870edba5e1891e92c/sdk-extensions/jaeger-remote-sampler/src/main/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/JaegerRemoteSampler.java#L130-L136

In these cases we include the stringified caught exception message and don't record the exception, preventing the user from seeing the stacktrace:

https://github.com/open-telemetry/opentelemetry-java/blob/9a992c2e6bd71735db55fc0870edba5e1891e92c/sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/internal/DefaultConfigProperties.java#L184-L185

https://github.com/open-telemetry/opentelemetry-java/blob/9a992c2e6bd71735db55fc0870edba5e1891e92c/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkBuilder.java#L504-L505

https://github.com/open-telemetry/opentelemetry-java/blob/9a992c2e6bd71735db55fc0870edba5e1891e92c/opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/TracerShim.java#L110-L114

https://github.com/open-telemetry/opentelemetry-java/blob/9a992c2e6bd71735db55fc0870edba5e1891e92c/sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/DeclarativeConfiguration.java#L290-L291

https://github.com/open-telemetry/opentelemetry-java/blob/9a992c2e6bd71735db55fc0870edba5e1891e92c/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkDoubleHistogram.java#L97-L98

https://github.com/open-telemetry/opentelemetry-java/blob/9a992c2e6bd71735db55fc0870edba5e1891e92c/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkLongHistogram.java#L102

We should add some guidance to https://github.com/open-telemetry/opentelemetry-java/blob/main/CONTRIBUTING.md#best-practices-that-we-follow to recommend not stringifying the exception and recording the exception using dedicated log overloads.

Comment (jack-berg) [reply exporters/common/src/main/java/io/opentelemetry/exporter/internal/grpc/GrpcExporter.java:136]: Opened #8228 to discuss / track separately.
