### PR TITLE
Make closing scope idempotent and noop when different context is active

### LINKED ISSUE #5055: Close scope is not idempotent
**Describe the bug**
The following test (with obviously wrong behavior) fails

```java
@Test
void closeTest()  {
    var span1 = getTracer().spanBuilder("foo").startSpan();
    var scope1 = span1.makeCurrent();
    var span2 = getTracer().spanBuilder("bar").startSpan();
    var scope2 = span2.makeCurrent();

    // span2 is current
    scope2.close();

    // span1 is current
    scope1.close();

     // no current span
    assertFalse(Span.current().getSpanContext().isValid());

    // !!!
    scope2.close();

    // fails here, span1 is current
    assertFalse(Span.current().getSpanContext().isValid());
}
```

What happens:
- scope2 captures span1 as 'before' state
- so any time scope2 is closed, it restores span1 and makes it current.

https://github.com/open-telemetry/opentelemetry-java/blob/5b497b115d567c725cb74dc1543f5e02e41b3fbf/context/src/main/java/io/opentelemetry/context/ThreadLocalContextStorage.java#L26-L41

**Steps to reproduce**
the test above

**What did you expect to see?**
Close should be idempotent - after scope is closed, calling close should be noop.

It's also strongly encouraged according to [docs](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html)

**What did you see instead?**
close is not idempotent.

**What version and what artifacts are you using?**
Artifacts: `opentelemetry-api`, `opentelemetry-sdk` 
Version: 1.21.0
How did you reference these artifacts? (excerpt from your `build.gradle`, `pom.xml`, etc)

```xml
<opentelemetry-version>1.21.0</opentelemetry-version>
...
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-sdk</artifactId>
            <version>${opentelemetry-version}</version>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-api</artifactId>
            <version>${opentelemetry-version}</version>
        </dependency>
```

**Environment**
Compiler: "AdoptOpenJDK 17.0.4.8"
OS: windows

**Additional context**
I'm trying to propagate spans in Camel (so that camel spans are correlated with spans from underlying libraries). Camel tracing is based on events that are not tracing-specific. Consequently, it's impossible (without significant refactoring) to guarantee that current span scope will be called exactly once. 
And while it's possible to implement idempotency with wrapping scope, OTel should do it out of the box.

It also seems that 

https://github.com/open-telemetry/opentelemetry-java/blob/5b497b115d567c725cb74dc1543f5e02e41b3fbf/context/src/main/java/io/opentelemetry/context/ThreadLocalContextStorage.java#L34-L39

 is a bit dangerous regardless of idempotency. Arguably, if `this.current() != toAttach` , it's best to do nothing or set an invalid context to minimize the side-effects of wrong operations with scope.

The proposal here is to do 

```java
      if (current() == toAttach) {
          THREAD_LOCAL_STORAGE.set(beforeAttach);
      } else {
        logger.log(
            Level.WARN,
            "Context in storage not the expected context, Scope.close was not called correctly");
     }
```

Another proposal is to remember the thread id span was made current on and do nothing when attempting to close scope on a different thread.
Otherwise, what happens is that 'before' span from the different thread leaks to another thread where it can no longer be closed.

### PR DESCRIPTION
**Pull request by lmolkova**
Fixes #5055

### CODE REVIEW

File: context/src/main/java/io/opentelemetry/context/ThreadLocalContextStorage.java [hunk 1]
```diff
@@ -30,14 +31,30 @@ public Scope attach(Context toAttach) {
...
-      if (current() != toAttach) {
+    return new ScopeImpl(beforeAttach, toAttach);
+  }
+
+  private class ScopeImpl implements Scope {
+    @Nullable private final Context beforeAttach;
+    private final Context toAttach;
+    private boolean closed;
+
+    private ScopeImpl(@Nullable Context beforeAttach, @Nonnull Context toAttach) {
```
Comment (jack-berg) [inline context/src/main/java/io/opentelemetry/context/ThreadLocalContextStorage.java:42]: `Nonnull` isn't needed because arguments are assumed to be nonnull unless indicated with `@Nullable`.

File: context/src/main/java/io/opentelemetry/context/ThreadLocalContextStorage.java [hunk 2]
```diff
@@ -30,14 +31,30 @@ public Scope attach(Context toAttach) {
...
+      this.beforeAttach = beforeAttach;
+      this.toAttach = toAttach;
+    }
+
+    @Override
+    public void close() {
+      if (!closed && current() == toAttach) {
```
Comment (jack-berg) [inline context/src/main/java/io/opentelemetry/context/ThreadLocalContextStorage.java:49]: Does `closed` need to be `AtomicBoolean` with `compareAndSet`?

Comment (lmolkova) [reply context/src/main/java/io/opentelemetry/context/ThreadLocalContextStorage.java:49]: My way of thinking is the following:
1. In general, scopes should only be closed on the same thread they were started on, so the whole scenario is single-threaded. And if not, then there are two other things to consider.
2. if the scope is closed, the second condition `current() == toAttach` should be false
3. with high concurrency, we can be in the  `!closed && current() == toAttach` branch more than once, but then we'd set the same result (`beforeAttach`), so it should be ok

so unless I'm missing something, we don't need atomic operations here and it's nice not to add any new overhead.

Comment (jack-berg) [reply context/src/main/java/io/opentelemetry/context/ThreadLocalContextStorage.java:48]: That reasoning makes sense to me 👍

**Review by jack-berg — APPROVED** [review]

**Review by mateuszrzeszutek — APPROVED** [review]

**Review by jkwatson — APPROVED** [review]
