### PR TITLE
Reduce usage of errorprone annotations to MustBeClosed.

### LINKED ISSUE #2897: Should error prone be included as a transitive dependency?
Because otherwise it can cause people issues with some compilation options.

FWIW Guava includes error prone as a transitive dependency, I suspect for similar reasons.

Here's an example:

https://github.com/trask/otel-java-error-prone-issue

(EDIT below: mvn _clean_ compile)

```
$ mvn clean compile
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------------< com.github.trask:test >------------------------
[INFO] Building test 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ test ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\git\testoteljava\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ test ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to C:\git\testoteljava\target\classes
[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING :
[INFO] -------------------------------------------------------------
[WARNING] Cannot find annotation method 'value()' in type 'com.google.errorprone.annotations.concurrent.GuardedBy': class file for com.google.errorprone.annotations.concurrent.GuardedBy not found
[INFO] 1 warning
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] warnings found and -Werror specified
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.143 s
[INFO] Finished at: 2021-02-03T17:27:48-08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project test: Compilation failure
[ERROR] warnings found and -Werror specified
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

### PR DESCRIPTION
**Pull request by anuraaga**
FWICT, `GuardedBy` is the only annotation that has the problem in #2897. But we can easily avoid it by using the JDK's annotation, which errorprone does support in the same way as its own.

We can't lose the killer `MustBeClosed` so I scoped the annotations down to only the context package to prevent accidentally using the wrong `GuardedBy` in others.

Fixes #2897

### CODE REVIEW

**Comment by anuraaga** [comment]
Note that if there was an issue with including `MustBeClosed` with `compileOnly`, then this build itself would fail, as I found when reworking the dependencies a bit while looking at it.

File: sdk/metrics/src/jmh/java/io/opentelemetry/sdk/metrics/MetricsTestOperationBuilder.java [hunk 1]
```diff
@@ -23,6 +22,7 @@
  * return a wrapper for both bound and unbound versions of that operation which can then be used in
  * a benchmark.
  */
+@SuppressWarnings("ImmutableEnumChecker")
```
Comment (bogdandrutu) [inline sdk/metrics/src/jmh/java/io/opentelemetry/sdk/metrics/MetricsTestOperationBuilder.java:25]: Why not adding the `javax.annotation` immutable annotation?

**Review by carlosalberto — APPROVED** [review]

File: sdk/metrics/src/jmh/java/io/opentelemetry/sdk/metrics/MetricsTestOperationBuilder.java (hunk 1 above)
Comment (anuraaga) [reply sdk/metrics/src/jmh/java/io/opentelemetry/sdk/metrics/MetricsTestOperationBuilder.java:25]: Error prone doesn't respect that. And this is only a test so suppressing seems fine.

Comment (bogdandrutu) [reply sdk/metrics/src/jmh/java/io/opentelemetry/sdk/metrics/MetricsTestOperationBuilder.java:25]: Ok

**Review by bogdandrutu — APPROVED** [review]

**Review by jkwatson — APPROVED** [review]
