### PR TITLE
Fix OkHttpGrpcSender to properly await executor shutdown

### LINKED ISSUE #7827: OkHttpGrpcSender.shutdown() does not properly await executor thread termination
**Describe the bug**

  The OkHttpGrpcSender.shutdown() method returns a CompletableResultCode that completes immediately, even though HTTP dispatcher threads are still running in the background. This
  violates the semantic contract of CompletableResultCode, where callers expect to use .join() to wait for async operations to fully complete.

**Steps to reproduce**

  Create an OkHttpGrpcSender, make some HTTP requests to trigger thread creation, call shutdown().join(), then enumerate running threads. HTTP dispatcher threads will still be alive
  despite the shutdown completing successfully.

**What did you expect to see?**

I expected .join() to wait for all threads to complete

**What did you see instead?**

HTTP dispatcher threads are still alive. 

**What version and what artifacts are you using?**

opentelemetry-java version 79f8691b8b094adeb04170cb857863fee46e4597

**Environment**

I believe I can reproduce on all environments, but mainly for the moment, Mac with these options

------------------------------------------------------------
Gradle 9.2.0
------------------------------------------------------------

Build time:    2025-10-29 13:53:23 UTC
Revision:      d9d6bbce03b3d88c67ef5a0ff31f7ae5e332d6bf

Kotlin:        2.2.20
Groovy:        4.0.28
Ant:           Apache Ant(TM) version 1.10.15 compiled on August 25 2024
Launcher JVM:  21.0.9 (Homebrew 21.0.9)
Daemon JVM:    /opt/homebrew/Cellar/openjdk@21/21.0.9/libexec/openjdk.jdk/Contents/Home (no JDK specified, using current Java home)
OS:            Mac OS X 15.6 aarch64

**Additional context**

I have a patch prepared but wanted to be complete and file an issue for discussion as well.

### PR DESCRIPTION
**Pull request by kevinburkesegment**
OkHttpGrpcSender.shutdown() was calling shutdownNow() on the dispatcher's ExecutorService but not waiting for threads to actually terminate. This caused two issues:

1. The CompletableResultCode returned immediately (ofSuccess()), even though background threads were still running
2. Applications that wait for all threads to complete before exiting would hang, as HTTP call threads remained alive

The original implementation:

- Called executorService.shutdownNow() to interrupt threads
- Immediately returned CompletableResultCode.ofSuccess()
- Did not call awaitTermination() to wait for threads to finish

This violated the semantic contract of CompletableResultCode, where callers expect to use .join() to wait for async operations to complete.

Modified OkHttpGrpcSender.shutdown() to:

1. Use shutdownNow() to interrupt idle threads immediately (safe since we've already called cancelAll() on pending work)
2. Create a background daemon thread that calls awaitTermination()
3. Complete the CompletableResultCode only after threads terminate (or timeout after 5 seconds)

This ensures callers who use .join() will wait for actual thread termination, not just shutdown initiation.

One limitation: OkHttp's internal TaskRunner threads (used for connection keep-alive) may remain alive temporarily. These are:

- Daemon threads (won't prevent JVM exit)
- Idle (in TIMED_WAITING state)
- Unable to receive new work after shutdown
- Will terminate after their 60-second keep-alive timeout

The test verifies that HTTP call threads (dispatcher executor threads) are properly terminated, which is the critical requirement.

Added OkHttpGrpcSenderTest.shutdown_ShouldTerminateExecutorThreads() which verifies:

- Dispatcher threads are terminated after shutdown
- CompletableResultCode completes successfully
- TaskRunner daemon threads are acknowledged but not required to terminate

Fix environment-dependent test failures:

Fixed four tests that were failing due to OS/JDK-specific networking behavior differences:

1. RetryInterceptorTest.connectTimeout() and nonRetryableException(): Changed to accept both SocketTimeoutException and SocketException, as different environments throw different exceptions when connecting to non-routable IPs

2. JdkHttpSenderTest.sendInternal_RetryableConnectTimeoutException(): Changed to accept both HttpConnectTimeoutException and IOException, as the specific exception varies by environment

3. AbstractGrpcTelemetryExporterTest.connectTimeout(): Increased timeout threshold from 1s to 6s to account for OS-specific variations in connection failure timing (was failing before shutdown changes, pre-existing flaky test)

Fixes #7827.

### CODE REVIEW

File: exporters/sender/okhttp/src/main/java/io/opentelemetry/exporter/sender/okhttp/internal/OkHttpGrpcSender.java [hunk 1]
```diff
@@ -213,10 +214,34 @@ private static String grpcMessage(Response response) {
...
+
+      // Wait for threads to terminate in a background thread
+      CompletableResultCode result = new CompletableResultCode();
+      Thread terminationThread =
+          new Thread(
+              () -> {
+                try {
+                  // Wait up to 5 seconds for threads to terminate
+                  // Even if timeout occurs, we succeed since these are daemon threads
+                  executorService.awaitTermination(5, TimeUnit.SECONDS);
```
Comment (jkwatson) [inline exporters/sender/okhttp/src/main/java/io/opentelemetry/exporter/sender/okhttp/internal/OkHttpGrpcSender.java]: If it fails to terminate in 5s, is it worth logging something?

Comment (kevinburkesegment) [reply exporters/sender/okhttp/src/main/java/io/opentelemetry/exporter/sender/okhttp/internal/OkHttpGrpcSender.java]: Added a log line at level warning

**Review by jkwatson — APPROVED** [review]
Seems good to me. @jack-berg do you want to give it a once over as well?

File: exporters/sender/jdk/src/test/java/io/opentelemetry/exporter/sender/jdk/internal/JdkHttpSenderTest.java [hunk 2]
```diff
@@ -99,7 +99,10 @@ void testShutdownException() throws Exception {
   @Test
   void sendInternal_RetryableConnectTimeoutException() throws IOException, InterruptedException {
     assertThatThrownBy(() -> sender.sendInternal(new NoOpMarshaler()))
-        .isInstanceOf(HttpConnectTimeoutException.class);
+        .satisfies(
+            e ->
+                assertThat((e instanceof HttpConnectTimeoutException) || (e instanceof IOException))
+                    .isTrue());
```
Comment (jack-berg) [inline exporters/sender/jdk/src/test/java/io/opentelemetry/exporter/sender/jdk/internal/JdkHttpSenderTest.java:105]: What about the changes to the source code require a change to this or `RetryInterceptorTest`?

File: exporters/sender/okhttp/src/test/java/io/opentelemetry/exporter/sender/okhttp/internal/OkHttpGrpcSenderTest.java [hunk 3]
```diff
@@ -56,4 +64,150 @@ private static Response createResponse(int httpCode, String grpcStatus, String m
...
+    // Send a request to trigger thread creation
+    CompletableResultCode sendResult = new CompletableResultCode();
+    sender.send(new TestMarshaler(), response -> sendResult.succeed(), error -> sendResult.fail());
+
+    // Give threads time to start
+    Thread.sleep(500);
+
+    // Capture OkHttp threads before shutdown
+    Set<Thread> threadsBeforeShutdown = getOkHttpThreads();
+    logger.info(
```
Comment (jack-berg) [inline exporters/sender/okhttp/src/test/java/io/opentelemetry/exporter/sender/okhttp/internal/OkHttpGrpcSenderTest.java]: Let's get rid of these log statements. They just make for noisy build logs, which I'm in a never-ending battle to wrangle.

File: exporters/sender/okhttp/src/test/java/io/opentelemetry/exporter/sender/okhttp/internal/OkHttpGrpcSenderTest.java [hunk 4]
```diff
@@ -56,4 +64,150 @@ private static Response createResponse(int httpCode, String grpcStatus, String m
...
+      Thread thread = threads[i];
+      if (thread != null && thread.getName() != null) {
+        String name = thread.getName().toLowerCase(Locale.ROOT);
+        if (name.contains("okhttp") || name.contains("ok-http")) {
+          okHttpThreads.add(thread);
+        }
+      }
+    }
+    return okHttpThreads;
+  }
```
Comment (jack-berg) [inline exporters/sender/okhttp/src/test/java/io/opentelemetry/exporter/sender/okhttp/internal/OkHttpGrpcSenderTest.java]:
```suggestion
  private static Set<Thread> getOkHttpThreads() {
    return Thread.getAllStackTraces().keySet().stream()
        .filter(thread -> {
          String name = thread.getName().toLowerCase(Locale.ROOT);
          return name.contains("okhttp") || name.contains("ok-http");
        }).collect(toSet());
  }
```

File: exporters/sender/okhttp/src/test/java/io/opentelemetry/exporter/sender/okhttp/internal/OkHttpGrpcSenderTest.java [hunk 5]
```diff
@@ -56,4 +64,150 @@ private static Response createResponse(int httpCode, String grpcStatus, String m
...
+            + " threads: "
+            + threadsBeforeShutdown.stream()
+                .map(Thread::getName)
+                .collect(Collectors.joining(", ")));
+
+    // Verify threads exist
+    assertFalse(
+        threadsBeforeShutdown.isEmpty(), "Expected OkHttp threads to be present before shutdown");
+
+    // Call shutdown and wait for it to complete
```
Comment (jack-berg) [inline exporters/sender/okhttp/src/test/java/io/opentelemetry/exporter/sender/okhttp/internal/OkHttpGrpcSenderTest.java]: #nit a lot of these comments are self explanaotry. Hi AI 👋

File: exporters/sender/okhttp/src/test/java/io/opentelemetry/exporter/sender/okhttp/internal/OkHttpGrpcSenderTest.java [hunk 6]
```diff
@@ -56,4 +64,150 @@ private static Response createResponse(int httpCode, String grpcStatus, String m
...
+            + " alive dispatcher threads: "
+            + dispatcherThreads.stream().map(Thread::getName).collect(Collectors.joining(", ")));
+
+    // TaskRunner threads are OkHttp's internal idle daemon threads. They have a 60-second
+    // keep-alive and will terminate on their own. They're harmless since:
+    // 1. They're daemon threads (won't prevent JVM exit)
+    // 2. They're idle (in TIMED_WAITING state)
+    // 3. No new work can be dispatched to them after shutdown
+    // We log them for visibility but don't fail the test.
+    if (!taskRunnerThreads.isEmpty()) {
```
Comment (jack-berg) [inline exporters/sender/okhttp/src/test/java/io/opentelemetry/exporter/sender/okhttp/internal/OkHttpGrpcSenderTest.java]: Does this happen in practice? If so, then what are really testing here? We change the code to wait for up to 5 seconds to complete the `CompletableResultCode`, but can't actually write a test to verify that because daemon threads might take longer than that to shutdown. 🤷

File: exporters/sender/jdk/src/test/java/io/opentelemetry/exporter/sender/jdk/internal/JdkHttpSenderTest.java (hunk 2 above)
Comment (kevinburkesegment) [reply exporters/sender/jdk/src/test/java/io/opentelemetry/exporter/sender/jdk/internal/JdkHttpSenderTest.java:105]: When I run the tests on my Mac with `./gradlew test` I get errors that look like this:

```
RetryInterceptorTest > connectTimeout() FAILED
    java.lang.AssertionError:
    Expecting actual throwable to be an instance of:
      java.net.SocketTimeoutException
    but was:
      java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:318)
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
        ...(115 remaining lines not displayed - this can be changed with Assertions.setMaxStackTraceElementsDisplayed)
        at io.opentelemetry.exporter.sender.okhttp.internal.RetryInterceptorTest.connectTimeout(RetryInterceptorTest.java:191)
```

and 

```
> Task :exporters:sender:jdk:test FAILED

JdkHttpSenderTest > sendInternal_RetryableConnectTimeoutException() FAILED
    java.lang.AssertionError:
    Expecting actual throwable to be an instance of:
      java.net.http.HttpConnectTimeoutException
    but was:
      java.net.http.HttpTimeoutException: request timed out
        at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:953)
        at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:133)
        at io.opentelemetry.exporter.sender.jdk.internal.JdkHttpSenderTest.lambda$setup$0(JdkHttpSenderTest.java:57)
        ...(103 remaining lines not displayed - this can be changed with Assertions.setMaxStackTraceElementsDisplayed)
        at io.opentelemetry.exporter.sender.jdk.internal.JdkHttpSenderTest.sendInternal_RetryableConnectTimeoutException(JdkHttpSenderTest.java:102)
```

These changes allow the tests to pass. I can submit as a separate PR

File: exporters/sender/okhttp/src/test/java/io/opentelemetry/exporter/sender/okhttp/internal/OkHttpGrpcSenderTest.java (hunk 6 above)
Comment (kevinburkesegment) [reply exporters/sender/okhttp/src/test/java/io/opentelemetry/exporter/sender/okhttp/internal/OkHttpGrpcSenderTest.java]: Yeah, that's a fair point... I reworked the test to something much simpler, just checking the code at the point of shutdown. The test fails on tip and passes with the patch applied.

File: exporters/sender/okhttp/src/test/java/io/opentelemetry/exporter/sender/okhttp/internal/OkHttpGrpcSenderTest.java (hunk 5 above)
Comment (kevinburkesegment) [reply exporters/sender/okhttp/src/test/java/io/opentelemetry/exporter/sender/okhttp/internal/OkHttpGrpcSenderTest.java]: I did look through the patch before submitting it, agreed though... I removed a fair number of these. Sorry, Java is not my most fluent programming language

File: exporters/sender/okhttp/src/test/java/io/opentelemetry/exporter/sender/okhttp/internal/OkHttpGrpcSenderTest.java (hunk 4 above)
Comment (kevinburkesegment) [reply exporters/sender/okhttp/src/test/java/io/opentelemetry/exporter/sender/okhttp/internal/OkHttpGrpcSenderTest.java]: Done (needed a slight modification to `toSet()` to work)

File: exporters/sender/okhttp/src/test/java/io/opentelemetry/exporter/sender/okhttp/internal/OkHttpGrpcSenderTest.java (hunk 3 above)
Comment (kevinburkesegment) [reply exporters/sender/okhttp/src/test/java/io/opentelemetry/exporter/sender/okhttp/internal/OkHttpGrpcSenderTest.java]: Done

File: exporters/sender/jdk/src/test/java/io/opentelemetry/exporter/sender/jdk/internal/JdkHttpSenderTest.java (hunk 2 above)
Comment (jack-berg) [reply exporters/sender/jdk/src/test/java/io/opentelemetry/exporter/sender/jdk/internal/JdkHttpSenderTest.java:105]: No this is small enough that its fine. Glad to have more robust tests. 🙂

**Review by jack-berg — APPROVED** [review]
Thanks!

File: exporters/sender/okhttp/src/test/java/io/opentelemetry/exporter/sender/okhttp/internal/OkHttpGrpcSenderTest.java (hunk 6 above)
Comment (jack-berg) [reply exporters/sender/okhttp/src/test/java/io/opentelemetry/exporter/sender/okhttp/internal/OkHttpGrpcSenderTest.java]: look good!

**Comment by kevinburkesegment** [comment]
any chance I can get a pass on the code coverage? I tried adding a test to cover this, but it failed on the Windows builder... I can try to figure out something if you'd like

**Comment by jack-berg** [comment]
> any chance I can get a pass on the code coverage? I tried adding a test to cover this, but it failed on the Windows builder... I can try to figure out something if you'd like

You're good. Thanks for this!
