### PR TITLE
Validate the span id and trace id when creating the SpanContext

### LINKED ISSUE #2719: SpanContext does not respect the specification contract
Right now the `SpanContext` API says:

```java
  /**
   * Returns the trace identifier associated with this {@link SpanContext} as 32 character lowercase
   * hex String.
   *
   * @return the trace identifier associated with this {@link SpanContext} as lowercase hex.
   */
  String getTraceId();

  /**
   * Returns the span identifier associated with this {@link SpanContext} as 16 character lowercase
   * hex String.
   *
   * @return the span identifier associated with this {@link SpanContext} as 16 character lowercase
   *     hex (base16) String.
   */
  String getSpanId();
```

This is the contract that we offer to the users, which we do not enforce in the public constructor:

```java
SpanContext spanContext = SpanContext.create("foo", "bar", TraceFlags.getDefault(), TraceState.getDefault());
System.out.println(spanContext.getTraceId());  // THIS WILL NOT PRINT 32 lowercase hex.
System.out.println(spanContext.getTraceIdBytes());  // this will throw an exception
```

There may be callers that rely on the returned string to be `32 character lowercase hex String` and we cannot break them, so we need to validate the input received in the `create` method: either during creation or just before returning the value but we MUST validate the input.

### PR DESCRIPTION
**Pull request by jkwatson**
And, remove that extra validation from propagators.

I didn't remove it from the B3 Propagator(s) yet... that will take a bit more work to untangle.

Resolves #2719

### CODE REVIEW

File: api/all/src/main/java/io/opentelemetry/api/trace/ImmutableSpanContext.java [hunk 1]
```diff
@@ -14,21 +14,30 @@
...
       String spanIdHex,
       TraceFlags traceFlags,
       TraceState traceState,
       boolean remote) {
-    return new AutoValue_ImmutableSpanContext(
-        traceIdHex, spanIdHex, traceFlags, traceState, remote);
+    if (SpanId.isValid(spanIdHex) && TraceId.isValid(traceIdHex)) {
+      return createInternal(traceIdHex, spanIdHex, traceFlags, traceState, remote);
+    }
+    return createInternal(
```
Comment (bogdandrutu) [inline api/all/src/main/java/io/opentelemetry/api/trace/ImmutableSpanContext.java:39]: Should we return the INVALID SC?

Comment (bogdandrutu) [reply api/all/src/main/java/io/opentelemetry/api/trace/ImmutableSpanContext.java:39]: The reason is that it may seem strange to propagate flags and state but not one of the IDs if the other one is invalid

Comment (bogdandrutu) [reply api/all/src/main/java/io/opentelemetry/api/trace/ImmutableSpanContext.java:39]: So we either drop everything or we keep everything that is valid. I think the current implementation is in the middle and not ideal

File: api/all/src/main/java/io/opentelemetry/api/trace/ImmutableSpanContext.java [hunk 2]
```diff
@@ -14,21 +14,30 @@
...
           TraceId.getInvalid(),
           SpanId.getInvalid(),
           TraceFlags.getDefault(),
           TraceState.getDefault(),
           /* remote= */ false);
 
+  private static AutoValue_ImmutableSpanContext createInternal(
+      String traceId, String spanId, TraceFlags traceFlags, TraceState traceState, boolean remote) {
+    return new AutoValue_ImmutableSpanContext(
+        traceId, spanId, traceFlags, traceState, /* remote$= */ remote);
```
Comment (bogdandrutu) [inline api/all/src/main/java/io/opentelemetry/api/trace/ImmutableSpanContext.java:27]: Now that you calculate the isValid it can be a property in the AutoValue so no need to recalculate that or to use memoization.

Comment (bogdandrutu) [inline api/all/src/main/java/io/opentelemetry/api/trace/ImmutableSpanContext.java:27]: Consider to remove the comment `/* remote$= */` not needed

File: api/all/src/main/java/io/opentelemetry/api/trace/ImmutableSpanContext.java (hunk 1 above)
Comment (jkwatson) [reply api/all/src/main/java/io/opentelemetry/api/trace/ImmutableSpanContext.java:39]: There were tests depending on this behavior. I'll need to figure out what they were trying to accomplish.

Comment (bogdandrutu) [reply api/all/src/main/java/io/opentelemetry/api/trace/ImmutableSpanContext.java:39]: I think I know why. There are 2 cases:
1. is invalid hex string -  in this case I think we should return SpanContext.getInvalid()
2. is equal with TraceIs.getInvalid() - this is used in tests I guess, probably we should preserve all values.

Not sure if that is the behavior we want, but this is a guess for the problem.

Comment (jkwatson) [reply api/all/src/main/java/io/opentelemetry/api/trace/ImmutableSpanContext.java:39]: yes...this will take a bit of research that we can create a follow-up issue to deal with, I think.

File: api/all/src/main/java/io/opentelemetry/api/trace/ImmutableSpanContext.java (hunk 2 above)
Comment (jkwatson) [reply api/all/src/main/java/io/opentelemetry/api/trace/ImmutableSpanContext.java:27]: excellent idea. let's create an issue to track that optimization.

Comment (jkwatson) [reply api/all/src/main/java/io/opentelemetry/api/trace/ImmutableSpanContext.java:27]: it always baffles me when errorprone will complain about this, and when it won't. I'm sure I added it because errorprone complained, but there might have been some refactoring after that.

**Review by anuraaga — APPROVED** [review]

File: api/all/src/main/java/io/opentelemetry/api/trace/ImmutableSpanContext.java (hunk 1 above)
Comment (jkwatson) [reply api/all/src/main/java/io/opentelemetry/api/trace/ImmutableSpanContext.java:39]: Added #2751

File: api/all/src/main/java/io/opentelemetry/api/trace/ImmutableSpanContext.java (hunk 2 above)
Comment (jkwatson) [reply api/all/src/main/java/io/opentelemetry/api/trace/ImmutableSpanContext.java:27]: #2752

**Comment by jkwatson** [comment]
Added issues to track the optimization and investigation of the slightly strange half-way-valid usage.

**Comment by jkwatson** [comment]
Added issues to track the optimization and investigation of the slightly strange half-way-valid usage.
