### PR TITLE
Fix remove attributes from span after termination

### LINKED ISSUE #1195: It is possible to remove an attribute from a span that has ended
**Describe the bug**
It is possible to remove an attribute from a span that has ended

**Additional context**
This was introduced in #807 and I believe it was a mistake.

### PR DESCRIPTION
**Pull request by thisthat**
Resolves #1195

### CODE REVIEW

File: sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java [hunk 1]
```diff
@@ -172,6 +172,44 @@ public void setAttribute() {
     }
   }
 
+  @Test
+  public void setAttribute_afterEnd() {
+    Span.Builder spanBuilder = tracerSdk.spanBuilder(SPAN_NAME);
```
Comment (carlosalberto) [inline sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java:177]: Do you really need to add 5 attributes for this test? You could have a single item and assert that only that item remains afterwards, and make the test simpler/smaller.

Comment (carlosalberto) [reply sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java:177]: Oh, never mind. You are exercising all the attribute types.

File: sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java [hunk 2]
```diff
@@ -230,6 +268,37 @@ public void setAttribute_nullAttributeValue() throws Exception {
     assertThat(span.toSpanData().getAttributes()).isEmpty();
   }
 
+  @Test
+  public void setAttribute_nullAttributeValue_afterEnd() throws Exception {
+    Span.Builder spanBuilder = tracerSdk.spanBuilder(SPAN_NAME);
+    spanBuilder.setAttribute("emptyString", "");
+    spanBuilder.setAttribute("nullString", (AttributeValue) null);
```
Comment (carlosalberto) [inline sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java:275]: This will not be added anyway. Maybe we can keep only the values that will be really added? This makes the test more concise.

**Comment by carlosalberto** [comment]
Overall LGTM.

File: sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java (hunk 2 above)
Comment (thisthat) [reply sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java:275]: You're right! This is pointless since it is covered by another test!

File: sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java [hunk 3]
```diff
@@ -334,6 +334,10 @@ public void setAttribute(String key, AttributeValue value) {
     Preconditions.checkNotNull(key, "key");
     if (value == null || (value.getType().equals(STRING) && value.getStringValue() == null)) {
       synchronized (lock) {
+        if (hasEnded) {
```
Comment (jkwatson) [inline sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java:337]: why don't we just do this check once up front, rather than repeating the code here and below?

Comment (thisthat) [reply sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java:337]: I didn't want to introduce another `synchronized` block. But I guess you're right, it is better to do only once upfront!

Comment (jkwatson) [reply sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java:337]: I'd rather have one slightly larger synchronized block, rather than force jumping in and out of the synchronization twice in rapid succession. As long as you're doing very cheap operations, just putting all the logic in one synchronization context is going to be better.

Comment (bogdandrutu) [reply sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java:337]: But this one does not jump between synchronized.

Comment (jkwatson) [reply sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java:337]: I agree. I was just thinking forward to moving the ended check up-front, rather then duplicating that check.

Comment (bogdandrutu) [reply sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java:337]: Splitting the lock is incorrect. You need to make the check in the same lock sync to ensure that the condition does not change between the two synchronized sections

Comment (bogdandrutu) [reply sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java:337]: To clarify @jkwatson your proposal is correct but your concern should not be a preference should be a requirement because otherwise the code is incorrect :)

Comment (thisthat) [reply sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java:337]: You are right @bogdandrutu, I was thinking only to the case where the span already ended.

Comment (jkwatson) [reply sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java:337]: @bogdandrutu also true! I hadn't actually fully thought through the implementation, but you are absolutely correct.

Comment (bogdandrutu) [reply sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java:337]: Personally I am happy with the current code, but not opposed to change it based on @jkwatson suggestion. Up to you @thisthat :)

Comment (thisthat) [reply sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java]: I think having everything in a single synchronized block makes it easier to fully understand the method. 7cab1ee addressed this :wink:
