### PR TITLE
Fix OTLP metric exporter toBuilder() loosing temporality

### LINKED ISSUE #7276: OTLP metric exporter toBuilder() looses aggregation temporality
**Describe the bug**

Using `OtlpGrpc/HTTPMetricExporter.toBuilder()` should yield an exporter builder which remembers the originally configured temporality. At the moment, the returned builder uses the default temporality

**Steps to reproduce**

```
    OtlpHttpMetricExporter original = OtlpHttpMetricExporter.builder()
        .setAggregationTemporalitySelector(AggregationTemporalitySelector.deltaPreferred())
        .build();
    Assertions.assertThat(original.getAggregationTemporality(InstrumentType.COUNTER)).isEqualTo(
        AggregationTemporality.DELTA);

    OtlpHttpMetricExporter modified = original.toBuilder().build();

    //This assertion fails
    assertThat(modified.getAggregationTemporality(InstrumentType.COUNTER)).isEqualTo(
        AggregationTemporality.DELTA);
```

### PR DESCRIPTION
**Pull request by JonasKunz**
Fixes #7276.

### CODE REVIEW

File: exporters/otlp/all/src/test/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporterBuilderTest.java [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+
+import static org.assertj.core.api.Assertions.assertThat;
+
+import io.opentelemetry.sdk.common.export.MemoryMode;
+import io.opentelemetry.sdk.metrics.export.AggregationTemporalitySelector;
+import io.opentelemetry.sdk.metrics.export.DefaultAggregationSelector;
+import org.junit.jupiter.api.Test;
+import org.mockito.Mockito;
+
+public class OtlpHttpMetricExporterBuilderTest {
```
Comment (jack-berg) [inline exporters/otlp/all/src/test/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporterBuilderTest.java:16]: #nit: remove `public` modifier on test class and methods annotated with `@Test`. Its no longer needed as of junit5

File: exporters/otlp/all/src/test/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporterBuilderTest.java [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+        Mockito.mock(DefaultAggregationSelector.class);
+
+    OtlpHttpMetricExporter original =
+        OtlpHttpMetricExporter.builder()
+            .setMemoryMode(MemoryMode.IMMUTABLE_DATA)
+            .setAggregationTemporalitySelector(temporalitySelector)
+            .setDefaultAggregationSelector(defaultAggregationSelector)
+            .build();
+
+    OtlpHttpMetricExporter copy = original.toBuilder().build();
```
Comment (jack-berg) [inline exporters/otlp/all/src/test/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporterBuilderTest.java:32]: Should clean exporters afterwards to free the thread pools initialized by the underlying http client libraries

**Review by jack-berg — APPROVED** [review]
Just a couple minor comments. Thanks!
