### PR TITLE
Fix for Issue with bound instruments generating datapoints from no recordings.

### LINKED ISSUE #1453: Bound Metric Instruments create empty MetricData
**Describe the bug**
When binding a synchronous instrument, it records empty `MetricData` even though no metrics are recorded. This does not occur with the `BoundValueRecorder`.

**Steps to reproduce**
```
        Meter meter = OpenTelemetry.getMeterProvider().get("test","test:1.0.0");
        DoubleCounter counter = meter
                .doubleCounterBuilder("byte_received")
                .build();
        DoubleCounter.BoundDoubleCounter boundCounter = byteCounter.bind(Labels.empty());
        
        Collection<MetricData> data = OpenTelemetrySdk.getMeterProvider().getMetricProducer().collectAllMetrics();
        for(MetricData md : data) {
            System.out.println(md);
        }
```

**What did you expect to see?**
As with other instruments, points should be empty. 

**What did you see instead?**
Points contains a `DoublePoint` with the value 0.0.

**What version and what artifacts are you using?**
Artifacts: `opentelemetry-sdk`
Version: `v0.6.0`
How did you reference these artifacts?  `compile('io.opentelemetry:opentelemetry-sdk:0.6.0-SNAPSHOT')`

**Environment**
Compiler: n/a
OS: Windows 10

**Additional context**
None

### PR DESCRIPTION
**Pull request by jkwatson**
Fixes #1453 

The fix is to introduce an AtomicBoolean in the AbstractAggregator that tracks whether recordings have been made since the last reset was done. The ActiveBatcher queries the aggregator and if no recordings have been made, it skips generating metric points.

### CODE REVIEW

File: sdk/src/main/java/io/opentelemetry/sdk/metrics/aggregator/AbstractAggregator.java [hunk 1]
```diff
@@ -16,14 +16,22 @@
...
 package io.opentelemetry.sdk.metrics.aggregator;
 
+import java.util.concurrent.atomic.AtomicBoolean;
+
 abstract class AbstractAggregator implements Aggregator {
+  // Note: This is not 100% thread-safe. There is a race condition where recordings can
+  // be made in the moment between the reset and the setting of this field's value. In those
+  // cases, it is possible that a recording could be missed in a given recording interval, but
+  // it should be picked up in the next, assuming that more recordings are being made.
+  private final AtomicBoolean hasRecordings = new AtomicBoolean(false);
```
Comment (anuraaga) [inline sdk/src/main/java/io/opentelemetry/sdk/metrics/aggregator/AbstractAggregator.java:26]: Since we're not using CAS, this can just be `volatile boolean`.

File: sdk/src/main/java/io/opentelemetry/sdk/metrics/aggregator/AbstractAggregator.java [hunk 2]
```diff
@@ -38,12 +46,37 @@ public void mergeToAndReset(Aggregator other) {
   abstract void doMergeAndReset(Aggregator aggregator);
 
   @Override
-  public void recordLong(long value) {
-    throw new UnsupportedOperationException("This Aggregator does not support long values");
+  public final void recordLong(long value) {
+    hasRecordings.set(true);
```
Comment (anuraaga) [inline sdk/src/main/java/io/opentelemetry/sdk/metrics/aggregator/AbstractAggregator.java:50]: Isn't it better to set after recording since that's when it actually "has recordings"?

File: sdk/src/main/java/io/opentelemetry/sdk/metrics/aggregator/Aggregator.java [hunk 3]
```diff
@@ -57,4 +57,7 @@
    * @param value the new {@code double} value to be added.
    */
   void recordDouble(double value);
+
+  /** Whether there have been any recordings since this aggregator has been reset. */
+  boolean hasRecordings();
```
Comment (anuraaga) [inline sdk/src/main/java/io/opentelemetry/sdk/metrics/aggregator/Aggregator.java:62]: No particular preference but wondered if `isEmpty` is more idiomatic

File: sdk/src/main/java/io/opentelemetry/sdk/metrics/aggregator/AbstractAggregator.java (hunk 2 above)
Comment (jkwatson) [reply sdk/src/main/java/io/opentelemetry/sdk/metrics/aggregator/AbstractAggregator.java:50]: I've gone back and forth several times on this, trying to figure out which leads to the least-bad race condition when it happens. I think you're right, though; I'll swap it around.

File: sdk/src/main/java/io/opentelemetry/sdk/metrics/aggregator/AbstractAggregator.java (hunk 1 above)
Comment (jkwatson) [reply sdk/src/main/java/io/opentelemetry/sdk/metrics/aggregator/AbstractAggregator.java:26]: true enough. I tend to usually not use volatile, rather than the Atomics, but I don't have a really strong feeling either way. I think the performance is pretty much equal, IIRC. Although I have this feeling that that changed with java 14 and Atomics got much worse (/me goes to read his Java Specialists newsletters).

File: sdk/src/main/java/io/opentelemetry/sdk/metrics/aggregator/Aggregator.java (hunk 3 above)
Comment (jkwatson) [reply sdk/src/main/java/io/opentelemetry/sdk/metrics/aggregator/Aggregator.java:62]: In this case, I don't know that aggregators necessarily have a universal concept of "emptiness", so I went with something very semantically clear and domain-specific.

File: sdk/src/main/java/io/opentelemetry/sdk/metrics/aggregator/AbstractAggregator.java (hunk 2 above)
Comment (jkwatson) [reply sdk/src/main/java/io/opentelemetry/sdk/metrics/aggregator/AbstractAggregator.java]: done. thanks for the close look!

File: sdk/src/main/java/io/opentelemetry/sdk/metrics/aggregator/AbstractAggregator.java (hunk 1 above)
Comment (jkwatson) [reply sdk/src/main/java/io/opentelemetry/sdk/metrics/aggregator/AbstractAggregator.java]: updated.
