### PR TITLE
Instruments with names which are case-insensitive equal contribute to…

### LINKED ISSUE #5683: Fix instrument identity evaluation in MetricStorageRegistry#register
As discussed in this [comment](https://github.com/open-telemetry/opentelemetry-java/pull/5677#discussion_r1284849528_), there's a bug in our evaluation of instrument identity in MetricStorageRegistry#register(..). 

MetricStorageRegistry uses MetricDescriptor#equals(..) to determine if an existing metric storage should be used with a newly registered instrument. If yes, the new instrument's measurements will be merged with the existing. If no, a new storage is created and the instrument's measurements are associated with a new metric stream at collection.

I know of two things we're doing wrong:
- If instruments are the same except for the case of a name, there should be a single metric stream exported, with the name of the first registered.
- If instruments are the same except for advice, there should be a single metric stream exported, with the advice of the first registered. 

The proof of the first issue is that the following test code fails:
```
    InMemoryMetricReader reader = InMemoryMetricReader.create();
    meterProvider = SdkMeterProvider.builder().registerMetricReader(reader).build();

    meterProvider.get("meter").counterBuilder("Counter").ofDoubles().build().add(1);
    meterProvider.get("meter").counterBuilder("counter").ofDoubles().build().add(1);

    assertThat(reader.collectAllMetrics())
        .satisfiesExactly(
            metric ->
                assertThat(metric)
                    .hasName("Counter")
                    .hasDoubleSumSatisfying(
                        sum ->
                            sum.hasPointsSatisfying(
                                point ->
                                    point.hasValue(2))));
```
Can produce similar test code to illustrate the second issue.

### PR DESCRIPTION
**Pull request by jack-berg**
Resolves #5683.

Instruments with names which are case-insensitive equal contribute to same metric, advice is not part of instrument identity. 

Embodies the [comment here](https://github.com/open-telemetry/opentelemetry-specification/issues/3622#issuecomment-1671853516).

### CODE REVIEW

File: sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/descriptor/MetricDescriptor.java [hunk 1]
```diff
@@ -94,36 +94,35 @@ public String getAggregationName() {
...
+    if (o == this) {
+      return true;
+    }
+    if (o instanceof MetricDescriptor) {
+      MetricDescriptor that = (MetricDescriptor) o;
+      return this.getName().equalsIgnoreCase(that.getName())
+          && this.getDescription().equals(that.getDescription())
+          && this.getView().equals(that.getView())
+          && this.getSourceInstrument().equals(that.getSourceInstrument());
+    }
```
Comment (breedx-splk) [inline sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/descriptor/MetricDescriptor.java:125]: The `aggregationName` used in the previous implementation is part of the view, so that's why it's not needed here. Just remarking because it gave me a small pause.

File: sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/descriptor/MetricDescriptorTest.java [hunk 2]
```diff
@@ -67,116 +68,106 @@ void metricDescriptor_isCompatible() {
...
+            SourceInfo.fromCurrentStack(),
+            InstrumentDescriptor.create(
+                "name",
+                "description",
+                "foo",
+                InstrumentType.COUNTER,
+                InstrumentValueType.DOUBLE,
+                Advice.empty()));
+    assertThat(descriptor1).isNotEqualTo(descriptor2).doesNotHaveSameHashCodeAs(descriptor2);
+    // Different instrument source type is not equal
```
Comment (breedx-splk) [inline sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/descriptor/MetricDescriptorTest.java:146]: Each of these commented sections seems like it's actually testing for a separate thing. Why not make these into actually separate test methods then?

**Review by breedx-splk — APPROVED** [review]
LGTM just one comment about the test really. Thanks!

**Review by mateuszrzeszutek — APPROVED** [review]

File: sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/descriptor/MetricDescriptorTest.java (hunk 2 above)
Comment (jack-berg) [reply sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/descriptor/MetricDescriptorTest.java:146]: Yeah this about the code style question of whether a single unit test method should test multiple cases or just a single one. (I feel like we've talked about this before 😄)

Personally, I do both depending on the situation, mostly depending on how much setup there is for each case. If the setup is small, then splitting each case out into its own method feels like unnecessary boiler plate on the author and reduced readability. On the other hand, if there's lots of special setup and you have to do things like reset the state of mocks, then it becomes fairly obvious to split out into separate methods. There's plenty of examples of both strategies in this repo. In this particular test, I was refactoring an existing test so stuck with the existing pattern. But even if it was new, I probably would have opted to keep all the not equals cases in a single test.

**Review by jkwatson — APPROVED** [review]

File: sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/descriptor/MetricDescriptorTest.java (hunk 2 above)
Comment (breedx-splk) [reply sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/descriptor/MetricDescriptorTest.java:146]: > [...] feels like unnecessary boiler plate on the author and reduced readability. 

Until a test fails, and you have to dive into a line of code from a stack trace instead of quickly getting a meaningful test name that matches a method name.

> I was refactoring an existing test so stuck with the existing pattern

Yeah, I respect the need to limit change range in a single PR.

Comment (jack-berg) [reply sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/internal/descriptor/MetricDescriptorTest.java:146]: > Until a test fails, and you have to dive into a line of code from a stack trace instead of quickly getting a meaningful test name that matches a method name.

Assertj relieves this with the ability to name / describe assertions. Didn't use it here tho, but probably should in cases where a single test method verifies multiple cases.
