### PR TITLE
Fix Jaeger exporter system property config

### LINKED ISSUE #1408: Use the now standard ConfigBuilder for JaegerGrpcSpanExporter.Builder
Currently, `JaegerGrpcSpanExporter.Builder` uses the older form:

```
JaegerGrpcSpanExporter.Builder.fromEnv().build();
```

instead of the now standard ConfigBuilder, e.g. `ZipkinSpanExporter`:

```
ZipkinSpanExporter.newBuilder()
    .readEnvironmentVariables()
    .readSystemProperties()
    .build();
```

### PR DESCRIPTION
**Pull request by trask**
Currently, the Jaeger exporter uses system property names that look like env vars `JAEGER_ENDPOINT` / `JAEGER_SERVICE_NAME`, which has caused confusion for a couple of opentelemetry-javaagent users.

This fixes that by using the now standard `ConfigBuilder` for `JaegerGrpcSpanExporter.Builder` (and following the conventions from `ZipkinSpanExporter`).

Closes #1408

### CODE REVIEW

File: exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporter.java [hunk 1]
```diff
@@ -192,6 +193,19 @@ public Builder setChannel(ManagedChannel channel) {
...
+    /**
+     * Sets the jaeger endpoint. This will use the endpoint to assign a {@link ManagedChannel}
+     * instance to this builder.
+     *
+     * @param endpoint The Jaeger endpoint URL, ex. "jaegerhost:14250".
+     * @return this.
+     * @since 0.7.0
+     */
+    public Builder setEndpoint(String endpoint) {
+      setChannel(createChannel(endpoint));
```
Comment (bogdandrutu) [inline exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporter.java:205]: I would not create the channel here. I would set the default endpoint in the ctor of the builder. Then in `build()` will check if the channel was set externally otherwise would create a new channel from "endpoint".

It feels to my more natural.

Comment (trask) [reply exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporter.java]: Makes sense, done

File: exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporter.java [hunk 2]
```diff
@@ -182,7 +184,10 @@ public Builder setServiceName(String serviceName) {
     }
 
     /**
-     * Sets the managed chanel to use when communicating with the backend. Required.
+     * Sets the managed chanel to use when communicating with the backend.
+     *
+     * <p>Should use only one of {@link #setChannel(ManagedChannel)} or {@link
```
Comment (anuraaga) [inline exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporter.java:189]: Does it make sense to validate this point in build?

File: exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporter.java [hunk 3]
```diff
@@ -223,27 +251,12 @@ public static Builder fromEnv() {
      * @return a new exporter's instance.
      */
     public JaegerGrpcSpanExporter build() {
+      if (channel == null) {
```
Comment (anuraaga) [inline exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporter.java:254]: Think we should validate that endpoint is set to provide a better error message, guessing otherwise it's an NPE.

File: exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporter.java (hunk 2 above)
Comment (trask) [reply exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporter.java]: I updated this to match the OTLP exporter builders behavior and javadoc

File: exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporter.java (hunk 3 above)
Comment (trask) [reply exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporter.java:249]: oh, i just realized, endpoint has a default, so no need to validate here i think?

File: exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporter.java (hunk 2 above)
Comment (trask) [reply exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/JaegerGrpcSpanExporter.java]: changed it again, no longer quite matches OTLP exporter behavior/javadoc, but i think a bit better (because of the default on endpoint, it's easier to check if channel was set, and if not fall back to endpoint). i will update my OTLP exporter PR to match
