### PR TITLE
Change Sampler interface

### LINKED ISSUE #880: Sampler.shouldSample() has a wrong signature
According to the [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/sdk-tracing.md#shouldsample) `io.opentelemetry.sdk.trace.io.opentelemetry.sdk.trace.Sampler` should provide a `shouldSample` method that accepts:
- `SpanContext`
- `TraceId`
- `SpanId`
- Name of the `Span`
- `SpanKind` -> **missing**
- Initial set of `Attributes` for the `Span` -> **missing**
- Links associated with the `Span`

### PR DESCRIPTION
**Pull request by thisthat**
Fixes #880 changing the signature of `io.opentelemetry.sdk.trace.Sampler#shouldSample`

### CODE REVIEW

File: sdk/src/main/java/io/opentelemetry/sdk/trace/Samplers.java [hunk 1]
```diff
@@ -89,6 +90,8 @@ public Decision shouldSample(
         TraceId traceId,
         SpanId spanId,
         String name,
+        Span.Kind spanKind,
+        Collection<AttributeValue> attributes,
```
Comment (bogdandrutu) [inline sdk/src/main/java/io/opentelemetry/sdk/trace/Samplers.java]: We need the key, value here, don't we?

Comment (jkwatson) [reply sdk/src/main/java/io/opentelemetry/sdk/trace/Samplers.java]: oh yeah! Good catch. Yes, this needs to be the Map.

Comment (thisthat) [reply sdk/src/main/java/io/opentelemetry/sdk/trace/Samplers.java]: Oh my bad! I understood the specification to have access only to the values of the attributes.
