### PR TITLE
Make the OpenTelemetrySdk a subclass of DefaultOpenTelemetry

### LINKED ISSUE #2018: Setting custom TracerProvider breaks access to TracerSdkManagement
Adding the following test to `OpenTelemetrySdkTest` results in test failure:

```
  @Test
  void testTracerProviderAccess() {
    OpenTelemetrySdk openTelemetry = OpenTelemetrySdk.builder()
        .setTracerProvider(tracerProvider)
        .build();
    assertThat(openTelemetry.getTracerProvider()).isEqualTo(tracerProvider);
    assertThat(openTelemetry.getTracerManagement()).isNotNull();
  }
```

```
class io.opentelemetry.api.trace.TracerProvider$MockitoMock$1536679414 cannot be cast to class io.opentelemetry.sdk.OpenTelemetrySdk$ObfuscatedTracerProvider (io.opentelemetry.api.trace.TracerProvider$MockitoMock$1536679414 and io.opentelemetry.sdk.OpenTelemetrySdk$ObfuscatedTracerProvider are in unnamed module of loader 'app')
java.lang.ClassCastException: class io.opentelemetry.api.trace.TracerProvider$MockitoMock$1536679414 cannot be cast to class io.opentelemetry.sdk.OpenTelemetrySdk$ObfuscatedTracerProvider (io.opentelemetry.api.trace.TracerProvider$MockitoMock$1536679414 and io.opentelemetry.sdk.OpenTelemetrySdk$ObfuscatedTracerProvider are in unnamed module of loader 'app')
	at io.opentelemetry.sdk.OpenTelemetrySdk.getTracerManagement(OpenTelemetrySdk.java:116)
	at io.opentelemetry.sdk.OpenTelemetrySdkTest.testTracerProviderAccess(OpenTelemetrySdkTest.java:93)
```

It also breaks `testGlobalDefault` from the same class as it happens to run after the one above:

```
Trying to access global TracerSdkManagement but global TracerProvider is not an instance created by this SDK.
java.lang.IllegalStateException: Trying to access global TracerSdkManagement but global TracerProvider is not an instance created by this SDK.
	at io.opentelemetry.sdk.OpenTelemetrySdk.getGlobalTracerManagement(OpenTelemetrySdk.java:52)
	at io.opentelemetry.sdk.OpenTelemetrySdkTest.testGlobalDefault(OpenTelemetrySdkTest.java:36)
```

### PR DESCRIPTION
**Pull request by jkwatson**
We discussed this possibility several times, so I thought I'd give it a try.

Feedback welcome. This resolves #2018 as well.

### CODE REVIEW

**Review by anuraaga — COMMENTED** [review]
We discussed a bit offline but sending these out :)

File: sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java [hunk 1]
```diff
@@ -114,68 +85,44 @@ public Clock getClock() {
...
-    private ContextPropagators propagators = DefaultContextPropagators.builder().build();
-
-    private TracerProvider tracerProvider;
-    private MeterProvider meterProvider;
 
-    /**
-     * Sets the {@link TracerProvider} to use. This can be used to configure tracing settings by
-     * returning the instance created by a {@link TracerSdkProvider.Builder}.
-     *
-     * @see TracerSdkProvider#builder()
```
[the remark this answers is not in the document]
Comment (jkwatson) [reply sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java:144]: for sure. will restore.

File: sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java [hunk 2]
```diff
@@ -114,68 +85,44 @@ public Clock getClock() {
...
 
-    /**
-     * Sets the {@link MeterProvider} to use.. This can be used to configure tracing settings by
-     * returning the instance created by a {@link MeterSdkProvider.Builder}.
-     *
-     * @see MeterSdkProvider#builder()
-     */
     @Override
     public Builder setMeterProvider(MeterProvider meterProvider) {
-      requireNonNull(meterProvider, "meterProvider");
```
[the remark this answers is not in the document]
Comment (jkwatson) [reply sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java:161]: the super call has this already, so I don't think we need to duplicate it.

File: sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java [hunk 3]
```diff
@@ -208,34 +155,21 @@ public Builder setResource(Resource resource) {
...
-          tracerProvider = new ObfuscatedTracerProvider(tracerProviderFactory.create());
-        } else if (HAS_TRACING_SDK) {
-          tracerProvider =
-              new ObfuscatedTracerProvider(
-                  TracerSdkProvider.builder().setClock(clock).setResource(resource).build());
-        } else {
-          tracerProvider = TracerProvider.getDefault();
-        }
+      MeterProvider meterProvider = super.buildMeterProvider();
+      TracerProvider tracerProvider = super.buildTracerProvider();
```
[the remark this answers is not in the document]
Comment (jkwatson) [reply sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java]: I added a really terrible unit test for this.

File: sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (jkwatson) [reply sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java:144]: done

File: sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java [hunk 4]
```diff
@@ -158,24 +131,14 @@ public Builder setTracerProvider(TracerProvider tracerProvider) {
      */
     @Override
     public Builder setMeterProvider(MeterProvider meterProvider) {
-      requireNonNull(meterProvider, "meterProvider");
-      this.meterProvider = meterProvider;
+      super.setMeterProvider(meterProvider);
```
Comment (anuraaga) [inline sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java:134]: Should we go ahead and be consistent and only accept `MeterSdkProvider` here since our goal is for this class to only configure the SDK?

File: sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java [hunk 5]
```diff
@@ -114,39 +85,41 @@ public Clock getClock() {
...
+        .setMeterProvider(getMeterProvider())
         .setPropagators(getPropagators())
         .setClock(clock)
         .setResource(resource);
   }
 
   /** A builder for configuring an {@link OpenTelemetrySdk}. */
-  public static class Builder implements OpenTelemetryBuilder<Builder> {
+  public static class Builder extends DefaultOpenTelemetry.Builder {
     private Clock clock = MillisClock.getInstance();
```
Comment (anuraaga) [inline sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java:104]: For the below `null` checks to work I think these need to default to `null`

File: sdk/all/src/test/java/io/opentelemetry/sdk/OpenTelemetrySdkTest.java [hunk 6]
```diff
@@ -76,10 +76,38 @@ void testReconfigure() {
...
+  @Test
+  void testReconfigure_justClockAndResource() {
+    Resource resource = Resource.create(Attributes.builder().put("cat", "meow").build());
+    OpenTelemetrySdk openTelemetry =
+        OpenTelemetrySdk.builder().setClock(clock).setResource(resource).build();
+    TracerProvider unobfuscatedTracerProvider =
+        ((ObfuscatedTracerProvider) openTelemetry.getTracerProvider()).unobfuscate();
+
+    assertThat(unobfuscatedTracerProvider).isInstanceOf(TracerSdkProvider.class);
+    // this is not a great way to test this...
```
Comment (anuraaga) [inline sdk/all/src/test/java/io/opentelemetry/sdk/OpenTelemetrySdkTest.java:96]:
```suggestion
    // Since TracerProvider is in a different package, the only alternative to this reflective
    // approach would be to make the fields public for testing which is worse than this.
```

File: sdk/all/src/test/java/io/opentelemetry/sdk/OpenTelemetrySdkTest.java [hunk 7]
```diff
@@ -76,10 +76,38 @@ void testReconfigure() {
...
+    assertThat(unobfuscatedTracerProvider)
+        .extracting("sharedState")
+        .hasFieldOrPropertyWithValue("clock", clock)
+        .hasFieldOrPropertyWithValue("resource", resource);
+
+    assertThat(openTelemetry.getMeterProvider()).isInstanceOf(MeterSdkProvider.class);
+    // this is not awesome
```
Comment (anuraaga) [inline sdk/all/src/test/java/io/opentelemetry/sdk/OpenTelemetrySdkTest.java:103]:
```suggestion
    // Since MeterProvider is in a different package, the only alternative to this reflective
    // approach would be to make the fields public for testing which is worse than this.
```

File: sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java (hunk 5 above)
Comment (jkwatson) [reply sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java:104]: very good point! will fix.

File: sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java (hunk 4 above)
Comment (jkwatson) [reply sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java:134]: Yeah, that's probably a good idea. Better to enforce it now even if we don't need to, rather than have to break things later when we do.

**Review by anuraaga — APPROVED** [review]
Think there's just one point left about rejecting non-MeterSdkProvider but that doesn't have to happen now anyways. Thanks!

**Comment by jkwatson** [comment]
> Think there's just one point left about rejecting non-MeterSdkProvider but that doesn't have to happen now anyways. Thanks!

oh shoot. I just forgot to do this. I'll add that real quick so we can get this merged and move forward with the SDK configuration story.

**Comment by jkwatson** [comment]
> > Think there's just one point left about rejecting non-MeterSdkProvider but that doesn't have to happen now anyways. Thanks!
> 
> oh shoot. I just forgot to do this. I'll add that real quick so we can get this merged and move forward with the SDK configuration story.

done!

**Review by anuraaga — APPROVED** [review]
Nice
