### PR TITLE
Do not inject invalid SpanContext instances.

### LINKED ISSUE #1272: Propagation does not work well with invalid current span.
**Describe the bug**
When an invalid default span (such as returned from `Tracer.getCurrentSpan()` when there is none) is explicitly set e.g. with `Tracer.withSpan`, the HttpTraceContext propagates a header `traceparent: 00-00000000000000000000000000000000-0000000000000000-00`.

**Steps to reproduce**

The following code reproduces the issue (add e.g. to `DefaultTracerTest` in the api test package):

```java
   @Test
  public void testSpanContextPropagationCurrentSpanContext() {
    Context context =
        TracingContextUtils.withSpan(DefaultSpan.create(spanContext), Context.current());
    Scope scope = ContextUtils.withScopedContext(context);
    try {
      Span span = defaultTracer.spanBuilder(SPAN_NAME).startSpan();
      assertThat(span.getContext()).isSameInstanceAs(spanContext);
    } finally {
      scope.close();
    }
  }

  @Test
  public void propagateNoCurrentSpan() {
    final Tracer tracer = OpenTelemetry.getTracer("nospandemo");

    final Setter<Void> printSetter =
        new Setter<Void>() {
          @Override
          public void set(@Nullable Void carrier, String key, String value) {
            System.out.println(key + ": " + value);
          }
        };

    System.out.println("Propagate, no span.");
    OpenTelemetry.getPropagators().getHttpTextFormat().inject(Context.current(), null, printSetter);

    final Span currentSpan = tracer.getCurrentSpan();

    // ... Some code in between, possibly switching threads ...

    try (Scope _scope = tracer.withSpan(currentSpan)) {
      System.out.println("Propagate, invalid span.");
      OpenTelemetry.getPropagators()
          .getHttpTextFormat()
          .inject(Context.current(), null, printSetter);
    }
  }
```

**What did you expect to see?**

I expect the propagation framework to detect that there is nothing to inject in both cases, hence the following output:

```
Propagate, no span.

Propagate, invalid span.

```

**What did you see instead?**

The invalid span was propagated by the HttpTraceContext propagator.

```
Propagate, no span.

Propagate, invalid span.

traceparent: 00-00000000000000000000000000000000-0000000000000000-00
```

**What version and what artifacts are you using?**
master from a git checkout, commit 84f5a3eab01c269e43c4962c5acc04bfc97de09b

### PR DESCRIPTION
**Pull request by carlosalberto**
Fixes #1272 

I don't imagine we propagating invalid `SpanContext` instances with non-default TraceFlags/TraceState, hence the `isValid()` check, as opposed to compare against `SpanContext.getInvalid()` ;)

### CODE REVIEW

File: contrib/trace_propagators/src/main/java/io/opentelemetry/contrib/trace/propagation/B3PropagatorInjectorMultipleHeaders.java [hunk 1]
```diff
@@ -32,7 +32,7 @@
     Objects.requireNonNull(setter, "setter");
 
     Span span = TracingContextUtils.getSpanWithoutDefault(context);
-    if (span == null) {
+    if (span == null || !span.getContext().isValid()) {
```
Comment (iNikem) [inline contrib/trace_propagators/src/main/java/io/opentelemetry/contrib/trace/propagation/B3PropagatorInjectorMultipleHeaders.java:35]: Wouldn't the code be easier if you replace `TracingContextUtils.getSpanWithoutDefault` with `TracingContextUtils.getSpan` and then drop null check and use only `isValid`?

Comment (carlosalberto) [reply contrib/trace_propagators/src/main/java/io/opentelemetry/contrib/trace/propagation/B3PropagatorInjectorMultipleHeaders.java:35]: Yeah, I was thinking about it too. I guess I prefer to do a simple `null` check before doing a full check, i.e. `getContext()` + `isValid()` ;)

FWIW though, I'm thinking, after cases like these, to remove the `getSpanWithoutDefault()` overload (which I might end up doing after doing some context-prop updates).

Comment (Oberon00) [reply contrib/trace_propagators/src/main/java/io/opentelemetry/contrib/trace/propagation/B3PropagatorInjectorMultipleHeaders.java:35]: There might be propagators that do will be able to meaninfully inject something only based on TraceState, even for invalid trace and span IDs. So while an utility function would be good, I think the final decision should be left to the propagator.

Comment (carlosalberto) [reply contrib/trace_propagators/src/main/java/io/opentelemetry/contrib/trace/propagation/B3PropagatorInjectorMultipleHeaders.java:35]: > There might be propagators that will be able to meaningfully inject something only based on TraceState

Right, exactly, I had totally forgotten about this case :)

Comment (bogdandrutu) [reply contrib/trace_propagators/src/main/java/io/opentelemetry/contrib/trace/propagation/B3PropagatorInjectorMultipleHeaders.java:35]: The w3c standard says that traceparent must be present so I am worried that if that can be the case to only propagate tracestate

Comment (Oberon00) [reply contrib/trace_propagators/src/main/java/io/opentelemetry/contrib/trace/propagation/B3PropagatorInjectorMultipleHeaders.java:35]: Sure, this does not apply to W3C but maybe other propagators (vendor ones for example).
