### PR TITLE
Per spec change, allow start digit and @.  

### LINKED ISSUE #562: Allow tracestate to begin with a digit
The tracestate spec changed to allow tracestate identifier to begin with a digit.  Reference https://www.w3.org/TR/trace-context/#key and corresponding fix merged in this PR:
https://github.com/w3c/trace-context/pull/332

The Open Telemetry Tracestate should change its verification to allow start digits in tracestate identifiers.  It currently results in an exception like:

```
java.lang.IllegalArgumentException: Invalid key 1@nr
```

### PR DESCRIPTION
**Pull request by breedx-nr**
Fixes #562

Note: This also adds support for `@` vendor prefix inside the key.

### CODE REVIEW

**Comment by songy23** [comment]
Please sign the CLA.

**Comment by breedx-nr** [comment]
@songy23 Yup, did it!  Thanks.

File: api/src/main/java/io/opentelemetry/trace/Tracestate.java [hunk 1]
```diff
@@ -235,28 +235,35 @@ public static Entry create(String key, String value) {
 
   // Key is opaque string up to 256 characters printable. It MUST begin with a lowercase letter, and
   // can only contain lowercase letters a-z, digits 0-9, underscores _, dashes -, asterisks *, and
-  // forward slashes /.
+  // forward slashes /.  For multi-tenant vendor scenarios, an at sign (@) can be used to prefix the
```
Comment (tylerbenson) [inline api/src/main/java/io/opentelemetry/trace/Tracestate.java]: Is the `@` intended to denote a prefix or suffix?  Based on your test below, it seems more of a suffix.

Comment (jkwatson) [reply api/src/main/java/io/opentelemetry/trace/Tracestate.java]: it's a prefix for the vendor name (such as `12345@dd`)

**Comment by breedx-nr** [comment]
Any reviewers able to take a look at this?

File: api/src/main/java/io/opentelemetry/trace/Tracestate.java [hunk 2]
```diff
@@ -235,28 +235,35 @@ public static Entry create(String key, String value) {
...
-        || key.charAt(0) > 'z') {
+    if (key.length() > KEY_MAX_SIZE || key.isEmpty() || !isNumberOrDigit(key.charAt(0))) {
       return false;
     }
+    int atSeenCount = 0;
     for (int i = 1; i < key.length(); i++) {
       char c = key.charAt(i);
-      if (!(c >= 'a' && c <= 'z')
+      if (!isNumberOrDigit(c)
           && !(c >= '0' && c <= '9')
```
Comment (songy23) [inline api/src/main/java/io/opentelemetry/trace/Tracestate.java]: I think this condition is covered by the previous one.

Comment (jkwatson) [reply api/src/main/java/io/opentelemetry/trace/Tracestate.java]: I think so too.  Also, `isNumberOrDigit` is always negated (per IDEA warning). I'll fix both of these issues and update the PR for @breedx-nr

Comment (jkwatson) [reply api/src/main/java/io/opentelemetry/trace/Tracestate.java]: fixed and pushed

**Comment by adriancole** [comment]
title and eventual commit message should include the '@' as it is more notable than numeric prefix.

File: api/src/main/java/io/opentelemetry/trace/Tracestate.java [hunk 3]
```diff
@@ -235,28 +235,29 @@ public static Entry create(String key, String value) {
...
+    int atSeenCount = 0;
     for (int i = 1; i < key.length(); i++) {
       char c = key.charAt(i);
-      if (!(c >= 'a' && c <= 'z')
-          && !(c >= '0' && c <= '9')
-          && c != '_'
-          && c != '-'
-          && c != '*'
-          && c != '/') {
+      if (isNotNumberOrDigit(c) && c != '_' && c != '-' && c != '@' && c != '*' && c != '/') {
```
Comment (bogdandrutu) [inline api/src/main/java/io/opentelemetry/trace/Tracestate.java]: Add a TODO that it may worth having an array `bool[256] validBytes` that will remove a lot of jumps here.

Comment (breedx-nr) [reply api/src/main/java/io/opentelemetry/trace/Tracestate.java]: I would push back on this level of detailed optimization this early in a pre-alpha release cycle.  TODOs like that always clutter up the code, and a distant future developer optimizing this area of the code might have an even better approach.

In any case, the current code is walking `char`s not `byte`s so we'd want `boolean[65536]` to index with char or assume an 8-bit encoding and convert char to byte and hope that we don't get a negative byte...

I dunno, doesn't seem worth it to me, especially this early.

Comment (kittylyst) [reply api/src/main/java/io/opentelemetry/trace/Tracestate.java]: I would very much counsel against littering the code with that type of comment. Remember - almost by definition - the code which matters is that which comes out of the JIT. It will not look like this.

File: api/src/main/java/io/opentelemetry/trace/Tracestate.java [hunk 4]
```diff
@@ -235,28 +235,29 @@ public static Entry create(String key, String value) {
...
+      if ((c == '@') && (++atSeenCount > 1)) {
         return false;
       }
     }
     return true;
   }
 
+  private static boolean isNotNumberOrDigit(char ch) {
+    return (ch < 'a' || ch > 'z') && (ch < '0' || ch > '9');
+  }
```
Comment (kittylyst) [inline api/src/main/java/io/opentelemetry/trace/Tracestate.java]: I would normally write a test method like this in the positive sense "isNumberOrDigit()" and apply the logical negation at the usage site. I find it easier to debug that way. YMMV.

Comment (jkwatson) [reply api/src/main/java/io/opentelemetry/trace/Tracestate.java]: Yeah, in a moment of weakness, I listened to IDEA and changed it to the negative version, because all usages were negated. Happy to change it back. :)

Comment (jkwatson) [reply api/src/main/java/io/opentelemetry/trace/Tracestate.java]: fixed.

File: api/src/main/java/io/opentelemetry/trace/Tracestate.java (hunk 3 above)
Comment (bogdandrutu) [reply api/src/main/java/io/opentelemetry/trace/Tracestate.java]: Thanks to @adriancole for raising this issue and help.

As much as I am a believer in the JIT magic (not) I would like to see JMH benchmarks to prove me wrong. As I suggested I did not say to do it, just as an optimization opportunity and a way to do it.

I am not going to argue that it is good or bad suggestion because that is something we can prove with benchmarks (and yes I believe in benchmarks).

I don't think in general a to-do litter the code, a well written todo may explain why an implementation is done in a specific way or the other.

So I would suggest that we either benchmark now between the two implementation or we add a comment that we did not benchmark this but an alternative implementation may be considered ....

Comment (jkwatson) [reply api/src/main/java/io/opentelemetry/trace/Tracestate.java]: I added a todo to benchmark the key validation code.
