### PR TITLE
Make the getKey method on AttributeKey non-nullable

### LINKED ISSUE #1678: The getKey() method in the AttributeKey interface should not be marked as Nullable
I believe this was originally done to help AutoValue do something internally. We should fix it, as it is incorrect and should never be null.

### PR DESCRIPTION
**Pull request by jkwatson**
This was done by tricking AutoValue with a separate field for the storage.

resolves #1678

### CODE REVIEW

File: api/src/main/java/io/opentelemetry/common/AttributeKeyImpl.java [hunk 1]
```diff
@@ -17,15 +17,24 @@
...
 @AutoValue
 abstract class AttributeKeyImpl<T> implements AttributeKey<T> {
 
   static <T> AttributeKeyImpl<T> create(String key, AttributeType type) {
-    return new AutoValue_AttributeKeyImpl<>(key, type);
+    return new AutoValue_AttributeKeyImpl<>(type, key);
   }
 
+  @Override
+  public String getKey() {
```
Comment (anuraaga) [inline api/src/main/java/io/opentelemetry/common/AttributeKeyImpl.java:31]: But can't `key()` return null?

Comment (jkwatson) [reply api/src/main/java/io/opentelemetry/common/AttributeKeyImpl.java:31]: It can, but I really want the public API to have the getKey() be non-nullable. We can't have the API blow up with null keys, but we really want the API to signal that it should never be null. I'm open to other suggestions to solve this one.

Comment (anuraaga) [reply api/src/main/java/io/opentelemetry/common/AttributeKeyImpl.java:31]: Got it - yeah that's a corner case I've ran into before too. I wasn't sure that was the intention but makes sense to me. If we ever add nullness checking (want to!) we'll need some "nullness casts" for these cases, just as a future food for thought.

**Review by anuraaga — APPROVED** [review]

File: api/src/main/java/io/opentelemetry/common/AttributeKeyImpl.java (hunk 1 above)
Comment (jkwatson) [reply api/src/main/java/io/opentelemetry/common/AttributeKeyImpl.java:31]: Right now, we drop null keys, I believe, so this seems like a decent compromise. You can put null in there, but you'll never actually see a null-keyed attribute anywhere, since we throw them away.
