### PR TITLE
Prevent SDK from throwing on null instrumentation name

### LINKED ISSUE #1879: OpenTelemetry.getTracer(...) differs from API spec
**Describe the bug**
The `OpenTelemetry.getTracer(...)` [family of methods](https://www.javadoc.io/static/io.opentelemetry/opentelemetry-api/0.9.1/io/opentelemetry/OpenTelemetry.html#getTracer-java.lang.String-) claim to reject a `null` library name. [The spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#get-a-tracer) for obtaining a tracer indicates that invalid names such as `null` and empty string should lead to a default value.

This behavior (returning a default) is found when only the API is on the classpath, but the SDK rejects `null` and throws an exception.

**Steps to reproduce**
```java
OpenTelemetry.getGlobalTracer(null);
OpenTelemetrySdk.get().getTracer(null);
```

**What did you expect to see?**
I don't know what the right answer is, but it's odd to me that the API silently allows `null` (but documents it as invalid), while the SDK throws on `null`, and the spec suggests `null` should be silently handled.

**What version and what artifacts are you using?**
Artifacts: `opentelemetry-api`, `opentelemetry-sdk`
Version: `v0.9.1`, `0.10.0-SNAPSHOT`

### PR DESCRIPTION
**Pull request by MariusVolkhart**
Fixes #1879 

The first commit has the fix. The other 2 commits are more of a code cleanup based on changes made in the first commit, but are not strictly necessary to fix the issue.

### CODE REVIEW

File: sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/MeterSdkProvider.java [hunk 1]
```diff
@@ -29,6 +31,8 @@
  */
 public final class MeterSdkProvider implements MeterProvider {
 
+  private static final Logger logger = Logger.getLogger(MeterSdkProvider.class.getName());
+  private static final String defaultMeterName = "unknown";
```
[the remark this answers is not in the document]
Comment (bogdandrutu) [reply sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/MeterSdkProvider.java:35]: We follow the Google's style guide, so we should enforce not prefer :)

File: sdk/common/src/main/java/io/opentelemetry/sdk/internal/ComponentRegistry.java [hunk 2]
```diff
@@ -22,18 +22,6 @@
...
 
-  /**
-   * Returns the registered value associated with this name and {@code null} version if any,
-   * otherwise creates a new instance and associates it with the given name and {@code null}
-   * version.
-   *
-   * @param instrumentationName the name of the instrumentation library.
-   * @return the registered value associated with this name and {@code null} version.
-   */
-  public final V get(String instrumentationName) {
```
[the remark this answers is not in the document]
Comment (MariusVolkhart) [reply sdk/common/src/main/java/io/opentelemetry/sdk/internal/ComponentRegistry.java:33]: The method was no longer used by code within this repository after I changed how `MeterSdkProvider` and `TracerSdkProvider` worked. Since it is in the `internal` package, I figured it wasn't intended for public consumption, and rather than having the unused method in the repo, I removed it.

If I should leave it, please let me know and I'll happily undo the change to remove it :)

**Comment by MariusVolkhart** [comment]
@jkwatson Thanks for the review! I rebased, and made the changes you requested. The last 2 commits are new, the first 3 are unchanged.

File: sdk/common/src/main/java/io/opentelemetry/sdk/internal/ComponentRegistry.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (carlosalberto) [reply sdk/common/src/main/java/io/opentelemetry/sdk/internal/ComponentRegistry.java:33]: @MariusVolkhart I suggest undoing this change and removing it in a follow-up PR ;)

**Review by carlosalberto — APPROVED** [review]

File: sdk/common/src/main/java/io/opentelemetry/sdk/internal/ComponentRegistry.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (MariusVolkhart) [reply sdk/common/src/main/java/io/opentelemetry/sdk/internal/ComponentRegistry.java]: I've reverted my changes, so the `ComponentRegistry` is untouched. Thanks @carlosalberto

File: sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/MeterSdkProvider.java [hunk 3]
```diff
@@ -41,11 +45,16 @@ private MeterSdkProvider(Clock clock, Resource resource) {
...
+    return get(instrumentationName, null);
   }
 
   @Override
-  public MeterSdk get(String instrumentationName, String instrumentationVersion) {
+  public MeterSdk get(String instrumentationName, @Nullable String instrumentationVersion) {
+    // Per the spec, both null and empty are "invalid" and a "default" should be used.
+    if (instrumentationName == null || instrumentationName.isEmpty()) {
+      LOGGER.fine("Meter requested without instrumentation name.");
+      instrumentationName = DEFAULT_METER_NAME;
```
Comment (bogdandrutu) [inline sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/MeterSdkProvider.java:56]: I think this will be a common case, I would suggest to actually resolve this as a static variable and return the instance.

Comment (MariusVolkhart) [reply sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/MeterSdkProvider.java:56]: I'm not sure I understand. Are you suggesting a static `MeterSdk` to represent the default, rather than loading the cached instance from the registry? Are we OK with ignoring the potentially valid version number provided when returning the static instance?

I don't think we should use a static here. Firstly, we have the cache, and secondly, optimizing the code for what is supposed to be a "don't do this" use case seems wrong. If this will be a common case, then it feels like there should be [a stronger push on the spec](https://github.com/open-telemetry/opentelemetry-specification/issues/586) to make `null` a valid value.

Comment (bogdandrutu) [reply sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/MeterSdkProvider.java:56]: Just have a "private static Meter DEFAULT_METER = registry.get(DEFAULT_NAME, null)" and return that if no name instead of always asking the registry to return the value.

Comment (bogdandrutu) [reply sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/MeterSdkProvider.java:56]: I understand that this is a no in the specs, but I do believe users will do this a lot :)). We can do that later

Comment (bogdandrutu) [reply sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/MeterSdkProvider.java:56]: If we don't throw exception, user will use this most of the time, that is my theory

Comment (Oberon00) [reply sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/MeterSdkProvider.java:56]: Should we keep throwing an exception then? The instrumentation name should not be a dynamically generated string that can accidentally be null at runtime anyway.

Comment (MariusVolkhart) [reply sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/MeterSdkProvider.java:56]: I drafted #2036 which goes the route of not only throwing the exception in the SDK, but also in the API. By doing so, 3rd-party library authors who consume just the API are less likely to create a library that works until the application developer drops in the SDK.

Comment (jkwatson) [reply sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/MeterSdkProvider.java:56]: Unfortunately, we explicitly can't do what you put into #2036. We cannot break applications that have poorly written instrumentation in them.

Comment (Oberon00) [reply sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/MeterSdkProvider.java:56]: OK. But can we log a SEVERE at least? The logspam should be enough pressure to fix an empty instrumentation name hopefully.

Comment (jkwatson) [reply sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/MeterSdkProvider.java:56]: We definitely should not spam an end-application's logs, as this can crash the app (run out of disk space, etc). And, if the end-user's application is using a library with bad instrumentation built in to it, they may not even have the option of fixing it (and they may not even be using OpenTelemetry at all!)

Comment (MariusVolkhart) [reply sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/MeterSdkProvider.java:56]: My original motivation for opening this issue and submitting a PR was that I was instrumenting an internal library that another team consumes. It was unclear to me as a library author what value I was supposed to provide as the `instrumentationName`, so I tried `null`. The API accepted it without crashing! It wasn't until later, when I did some testing and added the SDK, that it crashed. That would have been the consuming team who publish the app.

As the author of a library, I _wish_ my code had failed when just the API artifact was on the classpath, or at least complained loudly about it to me. But, since the spec declares that `null` should be treated as "use a default", I made this PR to modify the SDK to be lenient (thereby matching the API).

___
I think this PR meets the requirements of the current spec. More importantly, it makes the SDK and API artifacts behave consistently on invalid inputs, so there are no surprises when the SDK is used with instrumented code. It does _not_ optimize for the case that the spec says is invalid, and it doesn't help developers adding instrumentation to "do it right". 

I'll happily try to improve documentation or samples to give both library developers and application developers a better idea of what a meaningful `instrumentationName` is for their use case, and why it is important. My "using Otel for the first time" experience is still relatively fresh in my memory.

**Comment by MariusVolkhart** [comment]
Rebased to resolve conflicts.

File: sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/MeterSdkProvider.java (hunk 3 above)
Comment (jkwatson) [reply sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/MeterSdkProvider.java:56]: I'm 100% ok with the SDK not blowing up when a null instrumentation name is used. But, we should not change the API parameter annotations to make it something that is "approved", nor should we make the API throw exceptions if a null name is passed in.

File: api/src/main/java/io/opentelemetry/api/metrics/MeterProvider.java [hunk 4]
```diff
@@ -43,5 +44,5 @@ static MeterProvider getDefault() {
    * @param instrumentationVersion The version of the instrumentation library.
    * @return a tracer instance.
    */
-  Meter get(String instrumentationName, String instrumentationVersion);
+  Meter get(String instrumentationName, @Nullable String instrumentationVersion);
```
Comment (anuraaga) [inline api/src/main/java/io/opentelemetry/api/metrics/MeterProvider.java:47]: @MariusVolkhart Thanks for this change - the implementation looks good, but I agree that we don't need to add the `@Nullable` annotation to parameters that, we defensively check, but still expect to not be `null`. Do you think you can remove the annotations?

Comment (MariusVolkhart) [reply api/src/main/java/io/opentelemetry/api/metrics/MeterProvider.java]: Done! :)

**Review by jkwatson — APPROVED** [review]
I think this is a fine step forward. Thanks!

**Comment by MariusVolkhart** [comment]
Rebased onto latest
