### PR TITLE
Do not allow adding attributes, links after startSpan.

### LINKED ISSUE #1197: It is possible to add a link to a span after it has been built.
**Describe the bug**
If you hold on to the SpanBuilder used to create the span, you can continue to add links after the span has started.

**Steps to reproduce**
```
        Span.Builder spanBuilder = tracerSdk.spanBuilder(SPAN_NAME);
    spanBuilder.addLink(DefaultSpan.getInvalid().getContext());

    //this should lock the links in place
    RecordEventsReadableSpan span = (RecordEventsReadableSpan) spanBuilder.startSpan();
    List<SpanData.Link> originalLinks = span.toSpanData().getLinks();
    int numberOfLinksBeforeAfterStart = originalLinks.size();

    //add another link to the builder
    spanBuilder.addLink(DefaultSpan.getInvalid().getContext());

    //this number is correct
    assertThat(numberOfLinksBeforeAfterStart).isEqualTo(span.toSpanData().getTotalRecordedLinks());
    //but, we actually added a link to the underlying collection, via the builder.
    assertThat(numberOfLinksBeforeAfterStart).isEqualTo(span.toSpanData().getLinks().size());
```

### LINKED ISSUE #1199: You can add attributes to a started span via the builder that created it
**Describe the bug**
When we start a span, we should make a copy of the attributes from the SpanBuilder, but instead we just use a reference to the Builder's collection. This means you can continue to add attributes via the Builder.

**Steps to reproduce**
```
    Span.Builder spanBuilder = tracerSdk.spanBuilder(SPAN_NAME);
    spanBuilder.setAttribute("attr1", "value1");

    // this should make a copy of the attributes from the builder
    RecordEventsReadableSpan span = (RecordEventsReadableSpan) spanBuilder.startSpan();
    Map<String, AttributeValue> startingAttributes = span.toSpanData().getAttributes();

    // add another link to the *builder*
    spanBuilder.setAttribute("attr2", "value2");

    // this number is correct
    assertThat(startingAttributes.size()).isEqualTo(1);
    // but, we actually added an attribute to the underlying collection, via the builder.
    assertThat(span.toSpanData().getAttributes().size()).isEqualTo(1);
```

### PR DESCRIPTION
**Pull request by bogdandrutu**
Fixes #1199 
Fixes #1197

### CODE REVIEW

File: sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java [hunk 1]
```diff
@@ -176,10 +173,16 @@
     Objects.requireNonNull(key, "key");
     if (value == null
         || (value.getType() == AttributeValue.Type.STRING && value.getStringValue() == null)) {
+      if (attributes == null) {
+        return this;
+      }
       attributes.remove(key);
-    } else {
-      attributes.put(key, value);
+      return this;
```
Comment (arminru) [inline sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java:180]: Could be simplified to `if null { remove } return;`

File: sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java [hunk 2]
```diff
@@ -84,7 +84,8 @@
   private final long startEpochNanos;
   // Set of recorded attributes. DO NOT CALL any other method that changes the ordering of events.
   @GuardedBy("lock")
-  private final AttributesMap attributes;
+  @Nullable
+  private AttributesMap attributes;
```
Comment (arminru) [inline sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java:88]: Why are `attributes` nullable but `links` aren't?

File: sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java [hunk 3]
```diff
@@ -177,6 +177,24 @@ public void changingAttributes_NoEffectAfterAddLink() {
...
+  @Test
+  public void addLink_NoEffectAfterStartSpan() {
+    Span.Builder spanBuilder = tracerSdk.spanBuilder(SPAN_NAME);
+    spanBuilder.addLink(sampledSpanContext);
+    RecordEventsReadableSpan span = (RecordEventsReadableSpan) spanBuilder.startSpan();
+    try {
+      assertThat(span.toSpanData().getLinks())
+          .containsExactly(
+              Link.create(sampledSpanContext, Collections.<String, AttributeValue>emptyMap()));
+      spanBuilder.addLink(sampledSpanContext);
```
Comment (arminru) [inline sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java:189]: You might want to use a different SpanContext here, otherwise the missing effect could also come from a check that links are not duplicated (or a set being used internally).

File: sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java [hunk 4]
```diff
@@ -384,6 +431,27 @@ public void droppingAttributes() {
     }
   }
 
+  @Test
+  public void addAttributes_OnlyViaSampler() {
```
Comment (arminru) [inline sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java:435]: 👍 for covering this!

File: sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java (hunk 2 above)
Comment (bogdandrutu) [reply sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java:88]: Links is a final argument because the `Span` does not have an API to add links (only the builder) so it is fine to just use emptyList (which is immutable) if no links were added to avoid all null checks. In the case of attributes if I use emptyMap does not give me any benefit because that is immutable so I still need to have all checks before adding elements to the map.

File: sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java (hunk 1 above)
Comment (bogdandrutu) [reply sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java]: Done.

File: sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java (hunk 4 above)
Comment (bogdandrutu) [reply sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java:435]: You are welcome :)

File: sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java (hunk 3 above)
Comment (bogdandrutu) [reply sdk/src/test/java/io/opentelemetry/sdk/trace/SpanBuilderSdkTest.java]: Done, also added a comment to explain.

File: sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java (hunk 2 above)
Comment (arminru) [reply sdk/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java:88]: Thanks for clarifying!
