### PR TITLE
Do not register periodic metric reader when exporter is null

### LINKED ISSUE #4164: Exception when shutting down PeriodicMetricReader
Nothing looks obviously wrong from the code (`exporter` is a final variable) but randomly noticed this stacktrace when shutting down

```
[otel.javaagent 2022-02-09 01:53:45:446 +0000] [Thread-0] WARN io.opentelemetry.sdk.metrics.export.PeriodicMetricReader - Exporter threw an Exception
java.lang.NullPointerException
        at io.opentelemetry.sdk.metrics.export.PeriodicMetricReader.getPreferredTemporality(PeriodicMetricReader.java:59)
        at io.opentelemetry.sdk.metrics.internal.export.CollectionInfo.getPreferredAggregation(CollectionInfo.java:34)
        at io.opentelemetry.sdk.metrics.internal.state.AsynchronousMetricStorage.collectAndReset(AsynchronousMetricStorage.java:147)
        at io.opentelemetry.sdk.metrics.internal.state.MeterSharedState.collectAll(MeterSharedState.java:59)
        at io.opentelemetry.sdk.metrics.SdkMeter.collectAll(SdkMeter.java:40)
        at io.opentelemetry.sdk.metrics.SdkMeterProvider$LeasedMetricProducer.collectAllMetrics(SdkMeterProvider.java:174)
        at io.opentelemetry.sdk.metrics.export.PeriodicMetricReader$Scheduled.doRun(PeriodicMetricReader.java:125)
        at io.opentelemetry.sdk.metrics.export.PeriodicMetricReader.shutdown(PeriodicMetricReader.java:77)
        at io.opentelemetry.sdk.metrics.SdkMeterProvider.shutdown(SdkMeterProvider.java:131)
        at io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder.lambda$build$9(AutoConfiguredOpenTelemetrySdkBuilder.java:345)
        at java.base/java.lang.Thread.run(Thread.java:829)
Exception in thread "Thread-0" java.lang.NullPointerException
        at io.opentelemetry.sdk.metrics.export.PeriodicMetricReader$Scheduled.shutdown(PeriodicMetricReader.java:147)
        at io.opentelemetry.sdk.metrics.export.PeriodicMetricReader.shutdown(PeriodicMetricReader.java:85)
        at io.opentelemetry.sdk.metrics.SdkMeterProvider.shutdown(SdkMeterProvider.java:131)
        at io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder.lambda$build$9(AutoConfiguredOpenTelemetrySdkBuilder.java:345)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

### PR DESCRIPTION
**Pull request by jack-berg**
Likely fixes #4164.

If a user configured OTLP metrics, but doesn't have the OTLP exporter on the classpath for the configured exporter, then a periodic metric reader will be registered with a `null` exporter, which causes errors.

### CODE REVIEW

File: sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java [hunk 1]
```diff
@@ -57,6 +57,11 @@ static void configureExporter(
         metricExporter = spiExporter;
     }
 
+    // exporter may be null in otlp case
```
Comment (anuraaga) [inline sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java:60]: Any idea why null away didn't catch this? Guess it must allow null into java Function :(

**Review by anuraaga — APPROVED** [review]

File: sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java (hunk 1 above)
Comment (jack-berg) [reply sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java:60]: > Any idea why null away didn't catch this

I was curious about that as well. There's a related [discussion](https://github.com/uber/NullAway/issues/387#issuecomment-609895020) that explains that `Function` is maximally permissive, with `@Nullable` parameters and `@NonNull` response.
