### PR TITLE
Make the IntervalMetricReader robust to exporter failures

### LINKED ISSUE #1324: IntervalMetricReader should protect itself against exporters throwing exceptions
If a MetricExporter throws an exception, the IntervalMetricReader does not report the exception, and the scheduled thread exception will be halted.

The IMR should make sure to catch and report exceptions thrown by exporters.

### PR DESCRIPTION
**Pull request by jkwatson**
resolves #1324

### CODE REVIEW

File: sdk/src/main/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReader.java [hunk 1]
```diff
@@ -202,11 +206,15 @@ private Exporter(InternalState internalState) {
 
     @Override
     public void run() {
-      List<MetricData> metricsList = new ArrayList<>();
-      for (MetricProducer metricProducer : internalState.getMetricProducers()) {
-        metricsList.addAll(metricProducer.getAllMetrics());
+      try {
+        List<MetricData> metricsList = new ArrayList<>();
+        for (MetricProducer metricProducer : internalState.getMetricProducers()) {
```
Comment (carlosalberto) [inline sdk/src/main/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReader.java:211]: Do we need this section to be in this `try` block too?

Comment (jkwatson) [reply sdk/src/main/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReader.java:211]: Perhaps not, but if anything in here fails, we don't want the IMR to die, so it felt safer just to put everything in the block.
