### PR TITLE
Mark all threads/pools as daemon.

### LINKED ISSUE #1093: BatchSpanProcessor starts foreground thread, blocks JVM shutdown
To reproduce, try the following minimal sample:

```java
 public static void main(String[] args) {
    BatchSpansProcessor.newBuilder(new SpanExporter() {
      @Override
      public ResultCode export(Collection<SpanData> spans) {
        return ResultCode.SUCCESS;
      }

      @Override
      public void shutdown() {

      }
    }).build();
  }
```

The JVM will keep running because the BatchSpanProcessor created a foreground thread. This is a real problem especially for auto-instrumentation where `TracerProvider.shutdown` is usually called from `java.lang.Runtime.addShutdownHook`, which would not get invoked if the JVM never shuts down.

CC @trask

### PR DESCRIPTION
**Pull request by johnbley**
Our SDK shouldn't prevent apps/cli tools/etc. from exiting.  Mark all threads/pools as daemon.
Closes #1093

### CODE REVIEW

File: sdk/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpansProcessor.java [hunk 1]
```diff
@@ -237,6 +237,7 @@ public BatchSpansProcessor build() {
 
   private static Thread newThread(Runnable runnable) {
     Thread thread = MoreExecutors.platformThreadFactory().newThread(runnable);
+    thread.setDaemon(true);
```
Comment (jkwatson) [inline sdk/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpansProcessor.java:240]: discussion on the very very similar #1094 says this needs to go inside the try block because security managers can make this illegal.

File: sdk_contrib/async_processor/src/main/java/io/opentelemetry/sdk/contrib/trace/export/DisruptorEventQueue.java [hunk 2]
```diff
@@ -249,6 +249,7 @@ private ThreadFactoryWithName(String threadName) {
     @Override
     public Thread newThread(Runnable runnable) {
       Thread thread = MoreExecutors.platformThreadFactory().newThread(runnable);
+      thread.setDaemon(true);
```
Comment (jkwatson) [inline sdk_contrib/async_processor/src/main/java/io/opentelemetry/sdk/contrib/trace/export/DisruptorEventQueue.java:252]: same. move into the try block

Comment (johnbley) [reply sdk_contrib/async_processor/src/main/java/io/opentelemetry/sdk/contrib/trace/export/DisruptorEventQueue.java]: Will do (to both).

File: sdk/src/main/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReader.java [hunk 3]
```diff
@@ -135,7 +136,13 @@ public IntervalMetricReader build() {
   @SuppressWarnings("FutureReturnValueIgnored")
   private IntervalMetricReader(InternalState internalState) {
     this.exporter = new Exporter(internalState);
-    this.scheduler = Executors.newScheduledThreadPool(1, MoreExecutors.platformThreadFactory());
+    this.scheduler =
+        Executors.newScheduledThreadPool(
+            1,
+            new ThreadFactoryBuilder()
+                .setDaemon(true)
```
Comment (jkwatson) [inline sdk/src/main/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReader.java:143]: since there is a (admittedly rare) security manager-induced failure mode here, can we add a comment to the javadoc for this class about it?

Comment (Oberon00) [reply sdk/src/main/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReader.java:144]: Note that if we do this here, then newThread will throw if setDaemon fails.

Comment (jkwatson) [reply sdk/src/main/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReader.java:144]: do we know how fast this fails? I think the javadoc addition should be good to document this fact. Might be good to have a custom threadfactory which will allow non-daemon access if it's forbidden. @johnbley any idea how difficult that would be?

**Comment by bogdandrutu** [comment]
@jkwatson I think the decision was to set demon in a try-catch statement https://github.com/open-telemetry/opentelemetry-java/pull/1094. Why did we change that?

**Comment by jkwatson** [comment]
> @jkwatson I think the decision was to set demon in a try-catch statement #1094. Why did we change that?

We didn't. That's what @johnbley has implemented. The ThreadFactory case is one that we hadn't tackled yet.

File: sdk/src/main/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReader.java (hunk 3 above)
Comment (bogdandrutu) [reply sdk/src/main/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReader.java:144]: Probably a better solution:
Implement our own ThreadFactory see what we did in OpenCensus https://github.com/census-instrumentation/opencensus-java/blob/master/impl_core/src/main/java/io/opencensus/implcore/internal/DaemonThreadFactory.java 

And always use that to produce threads :)

**Comment by bogdandrutu** [comment]
@jkwatson you are correct, too much "Context" today. I added a comment about what we did in OpenCensus which was nice and we were able to use that everywhere. That way we ensure all the threads are correctly created.

File: sdk/src/main/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReader.java (hunk 3 above)
Comment (jkwatson) [reply sdk/src/main/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReader.java:144]: Definitely strong agree on this one!

File: sdk/src/main/java/io/opentelemetry/sdk/common/DaemonThreadFactory.java [hunk 4]
```diff
@@ -0,0 +1,37 @@
...
+package io.opentelemetry.sdk.common;
+
+import com.google.common.util.concurrent.MoreExecutors;
+import java.util.concurrent.ThreadFactory;
+
+/**
+ * A {@link ThreadFactory} that delegates to {@code MoreExecutors.platformThreadFactory()} and marks
+ * all threads as daemon.
+ */
+public class DaemonThreadFactory implements ThreadFactory {
```
Comment (bogdandrutu) [inline sdk/src/main/java/io/opentelemetry/sdk/common/DaemonThreadFactory.java:26]: Can we enhance this a bit and accept a thread name prefix + a local atomic integer and name the thread prefix + "_" + atomicval++?

That way we encapsulate everything in this class. What do you think?

Comment (johnbley) [reply sdk/src/main/java/io/opentelemetry/sdk/common/DaemonThreadFactory.java:27]: It removed a fair amount of extraneous code elsewhere.
