### PR TITLE
Fix span setStatus

### LINKED ISSUE #6797: Fix Span#setStatus
As reported by @laurit, `Span#setStatus` [implementation](https://github.com/open-telemetry/opentelemetry-java/blob/8194c10b785b7f8d232b4bce0b5f70c91669201a/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkSpan.java#L420) doesn't conform to the [spec](https://github.com/open-telemetry/opentelemetry-specification/blame/0a78571045ca1dca48621c9648ec3c832c3c541c/specification/trace/api.md#L563-L590).

Notably:

- Status codes form a priority of `OK > ERROR > UNSET`, where a call to set a lower priority shouldn't be able to override a higher priority status. Currently, its possible for a call with `UNSET` and override `ERROR`. 
- Description should be ignored when status is not `ERROR`, but is not

### PR DESCRIPTION
**Pull request by jack-berg**
Resolves #6797.

Supersedes #6808.

### CODE REVIEW

File: sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkSpan.java [hunk 1]
```diff
@@ -434,10 +434,26 @@ public ReadWriteSpan setStatus(StatusCode statusCode, @Nullable String descripti
...
-      } else if (this.status.getStatusCode() == StatusCode.OK) {
+      }
+
+      // If current status is OK, ignore further attempts to change it
+      if (this.status.getStatusCode() == StatusCode.OK) {
         logger.log(Level.FINE, "Calling setStatus() on a Span that is already set to OK.");
         return this;
       }
+
+      // Ignore attempts ot set status to UNSET
```
Comment (trask) [inline sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkSpan.java:445]:
```suggestion
      // Ignore attempts to set status to UNSET
```

**Review by trask — APPROVED** [review]
