### PR TITLE
Fix marshaler self suppression error

### LINKED ISSUE #5239: java.lang.IllegalArgumentException: Self-suppression not permitted
Describe the bug
java.lang.IllegalArgumentException: Self-suppression not permitted
at io.opentelemetry.exporter.internal.marshal.Marshaler.b(Marshaler.java:4)
at io.opentelemetry.exporter.internal.okhttp.ProtoRequestBody.writeTo

Steps to reproduce
ProtoRequestBody
public void writeTo(BufferedSink paramBufferedSink) throws IOException {
this.marshaler.writeBinaryTo(paramBufferedSink.outputStream());
}

Marshaler
public final void writeBinaryTo(OutputStream paramOutputStream) throws IOException {
ProtoSerializer protoSerializer = new ProtoSerializer(paramOutputStream);
try {
writeTo(protoSerializer);
return;
} finally {
try {
protoSerializer.close();
} finally {
protoSerializer = null;
}
}
}

ProtoSerializer implements AutoCloseable, so close() will execute
public void close() throws IOException {
this.output.flush();
this.idCache.clear();
}

in Marshaler.writeBinaryTo(), try() and close() throw a same Throwable instance , so Throwable.addSuppressed() will throw new IllegalArgumentException(SELF_SUPPRESSION_MESSAGE, exception);

What version are you using?
1.21.1

### PR DESCRIPTION
**Pull request by jack-berg**
Resolves #5239.

### CODE REVIEW

File: exporters/common/src/main/java/io/opentelemetry/exporter/internal/marshal/ProtoSerializer.java [hunk 1]
```diff
@@ -187,8 +187,12 @@ public void writeSerializedMessage(byte[] protoSerialized, String jsonSerialized
 
   @Override
   public void close() throws IOException {
-    output.flush();
-    idCache.clear();
+    try {
+      output.flush();
+      idCache.clear();
+    } catch (IOException e) {
+      throw new IOException(e);
```
Comment (jkwatson) [inline exporters/common/src/main/java/io/opentelemetry/exporter/internal/marshal/ProtoSerializer.java:194]: I think this deserves a "why" comment in the code. :)

File: exporters/common/src/test/java/io/opentelemetry/exporter/internal/marshal/MarshalerTest.java [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+    IOException error = new IOException("error!");
+    doThrow(error).when(os).write(any(), anyInt(), anyInt());
+    doThrow(error).when(os).write(any());
+    doThrow(error).when(os).write(anyInt());
+    doThrow(error).when(os).flush();
+
+    // If an exception is thrown writing bytes, and that same exception is thrown in the #close
+    // method
+    // cleaning up the AutoCloseable resource, an IllegalArgumentException will be thrown indicating
+    // illegal self suppression. Ensure an IOException is thrown instead.
```
Comment (jkwatson) [inline exporters/common/src/test/java/io/opentelemetry/exporter/internal/marshal/MarshalerTest.java:47]: formatting here is a bit odd... probably could use a bit of manual re-flowing of the text.

**Review by mateuszrzeszutek — APPROVED** [review]

**Review by jkwatson — APPROVED** [review]
