### PR TITLE
Fix flappy IntervalMetricReaderTest

### LINKED ISSUE #2340: Flaky Test: IntervalMetricReaderTest [x1]
This test fails occasionally with this error:

```
IntervalMetricReaderTest > intervalExport() FAILED
    java.lang.AssertionError: 
    Expecting:
      <[[MetricData{resource=Resource{attributes={}}, instrumentationLibraryInfo=InstrumentationLibraryInfo{name=IntervalMetricReaderTest, version=null}, name=my metric, description=my metric description, unit=us, type=DOUBLE_SUM, data=DoubleSumData{monotonic=true, aggregationTemporality=CUMULATIVE, points=[LongPoint{startEpochNanos=1000, epochNanos=3000, labels={}, value=1234567}]}}],
        [MetricData{resource=Resource{attributes={}}, instrumentationLibraryInfo=InstrumentationLibraryInfo{name=IntervalMetricReaderTest, version=null}, name=my metric, description=my metric description, unit=us, type=DOUBLE_SUM, data=DoubleSumData{monotonic=true, aggregationTemporality=CUMULATIVE, points=[LongPoint{startEpochNanos=1000, epochNanos=3000, labels={}, value=1234567}]}}],
        [MetricData{resource=Resource{attributes={}}, instrumentationLibraryInfo=InstrumentationLibraryInfo{name=IntervalMetricReaderTest, version=null}, name=my metric, description=my metric description, unit=us, type=DOUBLE_SUM, data=DoubleSumData{monotonic=true, aggregationTemporality=CUMULATIVE, points=[LongPoint{startEpochNanos=1000, epochNanos=3000, labels={}, value=1234567}]}}],
        [MetricData{resource=Resource{attributes={}}, instrumentationLibraryInfo=InstrumentationLibraryInfo{name=IntervalMetricReaderTest, version=null}, name=my metric, description=my metric description, unit=us, type=DOUBLE_SUM, data=DoubleSumData{monotonic=true, aggregationTemporality=CUMULATIVE, points=[LongPoint{startEpochNanos=1000, epochNanos=3000, labels={}, value=1234567}]}}]]>
    to contain exactly (and in same order):
      <[[MetricData{resource=Resource{attributes={}}, instrumentationLibraryInfo=InstrumentationLibraryInfo{name=IntervalMetricReaderTest, version=null}, name=my metric, description=my metric description, unit=us, type=DOUBLE_SUM, data=DoubleSumData{monotonic=true, aggregationTemporality=CUMULATIVE, points=[LongPoint{startEpochNanos=1000, epochNanos=3000, labels={}, value=1234567}]}}],
        [MetricData{resource=Resource{attributes={}}, instrumentationLibraryInfo=InstrumentationLibraryInfo{name=IntervalMetricReaderTest, version=null}, name=my metric, description=my metric description, unit=us, type=DOUBLE_SUM, data=DoubleSumData{monotonic=true, aggregationTemporality=CUMULATIVE, points=[LongPoint{startEpochNanos=1000, epochNanos=3000, labels={}, value=1234567}]}}]]>
    but some elements were not expected:
      <[[MetricData{resource=Resource{attributes={}}, instrumentationLibraryInfo=InstrumentationLibraryInfo{name=IntervalMetricReaderTest, version=null}, name=my metric, description=my metric description, unit=us, type=DOUBLE_SUM, data=DoubleSumData{monotonic=true, aggregationTemporality=CUMULATIVE, points=[LongPoint{startEpochNanos=1000, epochNanos=3000, labels={}, value=1234567}]}}],
        [MetricData{resource=Resource{attributes={}}, instrumentationLibraryInfo=InstrumentationLibraryInfo{name=IntervalMetricReaderTest, version=null}, name=my metric, description=my metric description, unit=us, type=DOUBLE_SUM, data=DoubleSumData{monotonic=true, aggregationTemporality=CUMULATIVE, points=[LongPoint{startEpochNanos=1000, epochNanos=3000, labels={}, value=1234567}]}}]]>
        at io.opentelemetry.sdk.metrics.export.IntervalMetricReaderTest.intervalExport(IntervalMetricReaderTest.java:88)
```

Examples:

* https://github.com/open-telemetry/opentelemetry-java/pull/2338/checks?check_run_id=1572439856

### PR DESCRIPTION
**Pull request by breedx-splk**
This resolves #2340

### CODE REVIEW

**Review by anuraaga — APPROVED** [review]

File: sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReaderTest.java [hunk 1]
```diff
@@ -176,20 +173,12 @@ public CompletableResultCode shutdown() {
...
-        while (exportedMetrics.size() < numberOfExports) {
-          try {
-            monitor.wait();
-          } catch (InterruptedException e) {
-            // Preserve the interruption status as per guidance.
-            Thread.currentThread().interrupt();
-            return null;
-          }
-        }
-        result = exportedMetrics;
```
Comment (anuraaga) [inline sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReaderTest.java:191]: IIUC, the problem was that exportedMetrics could have more than the expected number of exports returned? Anyways, blockingqueue always better than monitors!

**Review by anuraaga — APPROVED** [review]

File: sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReaderTest.java (hunk 1 above)
Comment (breedx-splk) [reply sdk/metrics/src/test/java/io/opentelemetry/sdk/metrics/export/IntervalMetricReaderTest.java:191]: Yeah, in some circumstances `export()` was entered a second time before the released `wait()` in the other thread could continue on with its work of adding to the result.  By the time it got around to doing that, there would occasionally be more data than expected.
