### PR TITLE
Fix opencensus shim spanBuilderWithRemoteParent behavior

### LINKED ISSUE #5475: opencensus-shim OpenTelemetrySpanBuilderImpl.startSpan() doesn't set underlying parent when passed remote context
**Describe the bug**
When using the opencensus-shim, and thus the OpenCensus APIs, after injecting an incoming propagated context and creating a span, the created span doesn't have the same trace id as the propagated context.
```scala
val spanContext: SpanContext = ??? // parsed from incoming request with propagated trace info
val span = Tracing.getTracer
  .spanBuilderWithRemoteParent(spanName, spanContext)
  .startSpan()
// span.getContext.getTraceId != spanContext.getTraceid
```
This is because the shim's `OpenTelemetrySpanBuilderImpl` [doesn't use the remote context to set the span's parent](https://github.com/open-telemetry/opentelemetry-java/blob/main/opencensus-shim/src/main/java/io/opentelemetry/opencensusshim/OpenTelemetrySpanBuilderImpl.java#L142). (The only way to set the parent span is to invoke `spanBuilderWithExplicitParent`).

The underlying OpenTelemetry impl of a `SpanBuilder` [only sets the parent if a parent span is provided](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkSpanBuilder.java#L180).

**Steps to reproduce**
See above.

**What did you expect to see?**
I expect that a child span of a `spanBuilderWithRemoteParent` has the same trace id as that of the parent context.

The legacy implementation in OpenCensus [properly sets the child's trace id to that of the parent context](https://github.com/census-instrumentation/opencensus-java/blob/baa68680b19040ff7739e314a2422a25cf41e27a/impl_core/src/main/java/io/opencensus/implcore/trace/SpanBuilderImpl.java#L194).

**What did you see instead?**
Child span doesn't have the same trace id as the parent when using the OpenCensus shim.

**What version and what artifacts are you using?**
Artifacts: `opentelemetry-api`, `opentelemetry-opencensus-shim`
Version: `v1.25.0`
How did you reference these artifacts? 

**Environment**
Compiler: openjdk version "17.0.7" 2023-04-18
OS: MacOSX 13.3

**Additional context**

### PR DESCRIPTION
**Pull request by jack-berg**
Fixes #5475.

The behavior of `spanBuilderWithRemoteParent` seems wrong right now. It adds a span link instead but does not set the span represented by the context argument to be the parent. Not sure why this is, but I can't find anything in the [opencensus compatibility spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/opencensus.md) which states that this is intended, so I'm going to assume its just a bug in the implementation.

### CODE REVIEW

**Review by gavin-nia — APPROVED** [review]
The change LGTM.

I tested this with a grpc client & server and verified that the final client span and first server span are correctly linked.

File: opencensus-shim/src/main/java/io/opentelemetry/opencensusshim/OpenTelemetrySpanBuilderImpl.java [hunk 1]
```diff
@@ -164,7 +164,11 @@ public Span startSpan() {
       otelSpanBuilder.setParent(Context.current().with((OpenTelemetrySpanImpl) ocParent));
     }
     if (ocRemoteParentSpanContext != null) {
-      otelSpanBuilder.addLink(SpanConverter.mapSpanContext(ocRemoteParentSpanContext));
+      io.opentelemetry.api.trace.SpanContext spanContext =
+          SpanConverter.mapSpanContext(ocRemoteParentSpanContext, /* isRemoteParent= */ true);
+      otelSpanBuilder.setParent(
+          Context.current().with(io.opentelemetry.api.trace.Span.wrap(spanContext)));
+      otelSpanBuilder.addLink(spanContext);
```
Comment (trask) [inline opencensus-shim/src/main/java/io/opentelemetry/opencensusshim/OpenTelemetrySpanBuilderImpl.java:171]: Why adding link also?

**Comment by trask** [comment]
> The change LGTM.
> 
> I tested this with a grpc client & server and verified that the final client span and first server span are correctly linked.

Thanks @gavin-nia, so we can tag this PR as Fixes #6416?

File: opencensus-shim/src/main/java/io/opentelemetry/opencensusshim/OpenTelemetrySpanBuilderImpl.java (hunk 1 above)
Comment (jack-berg) [reply opencensus-shim/src/main/java/io/opentelemetry/opencensusshim/OpenTelemetrySpanBuilderImpl.java:171]: Wasn't sure if anyone is dependent on the existing behavior.

Comment (trask) [reply opencensus-shim/src/main/java/io/opentelemetry/opencensusshim/OpenTelemetrySpanBuilderImpl.java:171]: Do you think we'd remove the `addLink` before marking the opencensus shim stable?

**Review by trask — APPROVED** [review]

File: opencensus-shim/src/main/java/io/opentelemetry/opencensusshim/OpenTelemetrySpanBuilderImpl.java (hunk 1 above)
Comment (jack-berg) [reply opencensus-shim/src/main/java/io/opentelemetry/opencensusshim/OpenTelemetrySpanBuilderImpl.java:171]: I'm not sure. I'd want the [spec opencensus compatibility doc](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/opencensus.md) to say what to do here before marking stable. That doc is currently lax on details which we see in the [opentracing compatibility doc](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/opentracing.md), so I don't see this happening any time soon.

**Comment by gavin-nia** [comment]
> > The change LGTM.
> > I tested this with a grpc client & server and verified that the final client span and first server span are correctly linked.
> 
> Thanks @gavin-nia, so we can tag this PR as Fixes #6416?

Yes, I believe so.
