### PR TITLE
Fix OpenTelemetryMetricExporterTest flake

### LINKED ISSUE #4646: OpenTelemetryMetricExporterTest flake
Build failed [here](https://github.com/open-telemetry/opentelemetry-java/runs/7563187459?check_suite_focus=true#step:5:575):
```
OpenTelemetryMetricExporterTest > testSupportedMetricsExportedCorrectly() FAILED
    org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in io.opentelemetry.opencensusshim.OpenTelemetryMetricExporterTest that uses io.opentelemetry.sdk.testing.exporter.InMemoryMetricExporter, io.opentelemetry.sdk.testing.exporter.InMemoryMetricExporterjava.util.Set, java.util.Setio.opencensus.tags.TagKey, io.opencensus.tags.TagKeyio.opencensus.tags.TagValue 
    Actual and expected should have same size but actual size is:
      32
    while expected size is:
      4
```

### PR DESCRIPTION
**Pull request by jack-berg**
Resolves #4646.

### CODE REVIEW

File: opencensus-shim/src/test/java/io/opentelemetry/opencensusshim/OpenTelemetryMetricExporterTest.java [hunk 1]
```diff
@@ -104,11 +104,16 @@ void testSupportedMetricsExportedCorrectly() throws Exception {
           .untilAsserted(
               () ->
                   assertThat(
+                          // Filter for metrics with name in allowedMetrics, and dedupe to only one
+                          // metric per unique metric name
```
Comment (jack-berg) [inline opencensus-shim/src/test/java/io/opentelemetry/opencensusshim/OpenTelemetryMetricExporterTest.java:108]: Was able to recreate the test flake by adding a `Thread.sleep(TimeUnit.SECONDS.toMillis(20))` above line 102. The test logic wasn't resilient to multiple metric exports taking place before the assertions are made.

**Review by jkwatson — APPROVED** [review]
